### ISSUE TITLE
Incompatible with latest version selenium webdriver 

### ISSUE THREAD

**Issue by joshuasiler** [rubyzip/rubyzip#115]
Works fine with selenium-webdriver v2.35.1, however when I upgrade to selenium-webdriver v2.38.0 I get "superclass mismatch for class File (TypeError)" in lib/zip/file.rb:45

Obviously maybe not your problem directly, but perhaps a less generic namespace would be helpful.

**Comment by dekaikiwi** [comment]
Still happening in 2018 :)

**Comment by MattEhrlich** [comment]
> Still happening in 2018 :) 
@dekaikiwi did you wind up moving zipruby gem to :development, :production only in gemfile?
