### ISSUE TITLE
Issue adding new file to existing zip

### ISSUE THREAD

**Issue by ThisOldCoder** [rubyzip/rubyzip#126]
Given two files in the current directory, foo.txt and bar.txt, with simple text contents, I execute the following statements from a Rails console:

This was in a freshly created Rails 4.0.1 app, using Ruby 2.0.0p247.

``` ruby
require 'zip'
Zip::File.open('foobar.zip', Zip::File::CREATE){|zip| zip.add('foo.txt', 'foo.txt')}
Zip::File.open('foobar.zip', Zip::File::CREATE){|zip| zip.add('bar.txt', 'bar.txt')}
```

All statements execute without error. After the first file is added, the resulting zip file will unzip normally. After the second, this is the result of attempting to unzip it:

```
Archive:  foobar.zip
  inflating: foo.txt                 
  error:  invalid compressed data to inflate
  inflating: bar.txt 
```

This is the output from a verbose list:

```
Archive:  foobar.zip
 Length   Method    Size  Ratio   Date   Time   CRC-32    Name
--------  ------  ------- -----   ----   ----   ------    ----
    2604  Defl:N     1074  59%  01-23-14 06:26  4d0296a1  foo.txt
    1382  Defl:N      777  44%  01-23-14 06:26  8525d182  bar.txt
--------          -------  ---                            -------
    3986             1851  54%                            2 files
```

I realize I can just add both files in the same block (which works), but this is just a greatly simplified example. In the actual application, we need to be able to add files to zips which may have been created hours, days, or weeks earlier.

**Comment by vimmisinghani** [comment]
i am still having same issue
