### ISSUE TITLE
AbstractInputStream#gets is very slow

### ISSUE THREAD

**Issue by mksm** [rubyzip/rubyzip#151]
Env:

ruby 2.0.0p195 (2013-05-14 revision 40734) [x86_64-linux]
rubyzip 1.1.2

Testing with:

``` ruby
input  = Zip::File.open(file).first.get_input_stream
output = Tempfile.new(self.name)

while not input.eof? do
  line = input.readline.strip
  # ...
end
```

Ran this with `-rprofile` and got:

```
 time   seconds   seconds    calls  ms/call  ms/call  name
 72.04    50.75     50.75     4634    10.95    10.95  String#slice!
  2.58    52.57      1.82      940     1.94     1.94  String#index
```

Some quick testing with pry got that `input.gets` was taking 0.1-0.2s to return. Wouldn't it be possible for InputStream to inherit IO's methods which are much faster?

Thanks for looking into this!

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by mksm** [comment]
Yeah, this is too old. We can close.
