### ISSUE TITLE
Zip::InputStream#gets reads entire entry into buffer

### ISSUE THREAD

**Issue by b-dean** [rubyzip/rubyzip#157]
The `gets` method is supposed to read until either:
- it reads the specified separator
- it reads the specified number of bytes
- it reads to the end of the file

It does not do this however. It reads the entire buffer into memory which will cause problems, especially with large files.

The problem is that once it gets into the part that is trying to read until it sees the separator, it uses `produce_input` which for `Zip::InputStream` just calls `Zip::Inflater#sysread` with no arguments, which reads the whole file.

https://github.com/rubyzip/rubyzip/blob/master/lib/zip/ioextras/abstract_input_stream.rb#L81

**Comment by hainesr** [comment]
I don't think there are any bare calls to `read`/`sysread` anymore. All seem to be passed a length/size as far as I can see.
