### ISSUE TITLE
incorrect filetime

### ISSUE THREAD

**Issue by McBen** [rubyzip/rubyzip#176]
times of newly added files are always zip-file creation date.

**Comment by agross** [comment]
I can confirm. It would be great if this could be fixed.

**Comment by agross** [comment]
This is my workaround:
https://github.com/agross/rake-funnel/commit/9c274bc1e4d6ef9d697f69e48166e0f34f16f7a8

**Comment by colderis** [comment]
:+1:

I use this gem to zip all the bills and send them to accounting and for them the creation date really matters.

Thanks @agross for the fix, I'll try it next week.

**Comment by agross** [comment]
@hainesr Closed means fixed?

**Comment by hainesr** [comment]
Yes, sorry should have left a note. Fixed on HEAD and the default is now to restore times on extraction too. Please let us know if not the case.
