### ISSUE TITLE
Ruby on Rails 4 error: private method `open' called for Zip::File:Class 

### ISSUE THREAD

**Issue by CrashPhoenix** [rubyzip/rubyzip#184]
Added a helper method to my Application controller:
```
  def unzip (file, destination)
  	Zip::File.open(file) do |zip_file|
			zip_file.each do |f|
				f_path = File.join(destination, f.name)
				FileUtils.mkdir_p(File.dirname(f_path))
				f.extract(f_path) 
			end
		end
  end
```
and I get the error "private method `open' called for Zip::File:Class"
How do I work around this issue?

**Comment by adamgamble** [comment]
I also have this same issue using 1.1.7 and rails 4.1.9. I think mine was caused by a gem using the outdated zipruby gem which also uses the Zip class. I think this is probably the problem for you also @CrashPhoenix. This doesn't appear to be an issue with rubyzip itself.

**Comment by swaz786** [comment]
#

**Comment by nengxu** [comment]
I encountered this error in Rails 5.2.2. ::Zip::File.open got the same error.

**Comment by nengxu** [comment]
It turned out to be caused by another similar gem zipruby. After turned it off, rubyzip works fine.
