### ISSUE TITLE
Encoding issue when opening DOCX

### ISSUE THREAD

**Issue by Skulli** [rubyzip/rubyzip#186]
I am using the gem docx_replace, which uses rubyzip for the docx manipulation.

In one line the content of the *word/document.xml* is read into memory via

    def read_docx_file
      @document_content = @zip_file.read(DOCUMENT_FILE_PATH)
    end

where *@zip_file* is a *Zip::File*
The encoding of the returned data is somehow *ASCII-8BIT*, even though the file itself is *UTF8* encoded.

As a workaround i extracted the file and opened it manually, see https://github.com/adamalbrecht/docx_replace/issues/8
which then returns the correct encoded data.

**Comment by lihlio** [comment]
@Skulli have you solve it ? i have the same problem with you.

**Comment by Skulli** [comment]
See here: https://github.com/adamalbrecht/docx_replace/issues/8


A *force_encoding("UTF-8")* on the content does also work for me.
