### ISSUE TITLE
Support Standard Zip Encryption and Decryption

### ISSUE THREAD

**Issue by johnnyshields** [rubyzip/rubyzip#194]
I would like to request to support Standard/Traditional Zip Encryption/Decryption in this library (sometimes called "ZipCrypto" or "Standard Encryption")

Currently there is a pull request here to support AES Decryption (AES is different than Standard encryption): https://github.com/rubyzip/rubyzip/pull/179

Requirements:
- Refer to the [Zip4j](http://www.lingala.net/zip4j/) Java implementation of this functionality, which is quite good. Also Ruby library https://github.com/javanthropus/archive-zip supports it.
- In particular we should add a `/lib/crypto` directory with `standard_encrypter.rb` and `standard_decrypter.rb` files that inherit from common `encrypter.rb` and `decrypter.rb` base classes, equivalent to `IEncypter.java` and `IDecrypter.java` in Zip4j, so that additional encryption types may be added in the future. Note that this structure is not present in the current work on #179.
- Must work with RubyZip's input and output streams methods. E.g. something like: 

```
      Zip::OutputStream.write_buffer do |out|
        out.put_next_entry("my_filename.csv", password: "foobar", encryption: "standard")
        out.write @my_csv_file
      end
```
- Code should be clean and must include README and unit/integration test cases. If you refer to #179 there was some discussion about how the cases should be written using fixtures zip files. We should also add a roundtrip test case (encrypt then decrypt)
- Output file must be able to be opened in standard Windows XP/7/8 without a third-party lib like 7zip.

**Comment by hainesr** [comment]
As far as I can see Rubyzip now supports ZipCrypto style encryption/decryption.
