### ISSUE TITLE
entry streams break when they aren't read immediately

### ISSUE THREAD

**Issue by recursive-madman** [rubyzip/rubyzip#196]
To reproduce:

``` ruby
require 'zip'

zip_stream = Zip::InputStream.new(File.open('test-zip.zip'))

entries = {}
while entry = zip_stream.get_next_entry
  entries[entry.name] = entry
end

stream_a = entries['file1'].get_input_stream
stream_b = entries['file2'].get_input_stream

stream_a.read
stream_b.read # << raises: buffer error (Zlib::BufError), from rubyzip-1.1.6/lib/zip/inflater.rb:43:in `inflate'
```

**Comment by hainesr** [comment]
I wonder if we should catch the buffer error, rewind and retry?

**Comment by hainesr** [comment]
Interestingly, using `Zip::File.open` to read the zip file seems to work without the rewind:
```ruby
zf = Zip::File.open('zipfile.zip')
stream_a = zf.get_input_stream('file1.txt')
stream_b = zf.get_input_stream('file2.txt')

stream_a.read
stream_b.read # Nothing raised
```

I'm now wondering if it's really a bug that the `InputStream` version shows this behaviour... `InputStream` is a bit more ephemeral, and generally one would get the stream and do something with it immediately.

Would appreciate thoughts.

**Comment by jspanjers** [comment]
I think the reason that Zip::InputStream exists is to read zip files from IO that is not seekable (and thus not rewindable).
That implies that when you use Zip::InputStream, you should only iterate over the entries and read its streams in the order that they appear in the IO.

I do not think it is really a bug in InputStream that it throws an error when you do not use it 'as intended'. It should be an other (more informative) error though.

**Comment by hainesr** [comment]
Agreed @jspanjers. I think a note in the README to this effect would also be useful. I'll have a think.
