### ISSUE TITLE
0600 ZIP file permissions with umask 0022

### ISSUE THREAD

**Issue by chillum** [rubyzip/rubyzip#204]
I do:

``` ruby
Zip::File.open(zip_file, Zip::File::CREATE) do |zip|
  begin
    zip.add(name, bin)
  rescue Zip::ZipEntryExistsError
    zip.replace(name, bin)
  end
end
```

Is there a reason, I get `0600` file permissions on my `zip_file` instead of `0644`, I would expect? Diagnostics:

``` sh
$ umask
0022
$ ruby --version 
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin12.0]
```

I googled that and found out an advice to use `File.chmod` implicitly. Am I overlooking something? In particular:
1. Why rubyzip does not default to `umask`-based permissions? Is it documented?
2. Are there any handles to get `umask`-based behaviour, not a hardcoded `0600`? Didn't find them in docs.

**Comment by gregawoods** [comment]
I agree with @hainesr. This behavior caught me by surprise today and it felt very unintuitive.

**Comment by simonoff** [comment]
There is no setting about default umask or something like this. Rubyzip uses `Tempfile` which created files with `0600`. So if you want to have support for default umask - please send PR.

**Comment by hainesr** [comment]
I did have a look at fixing this back in December. I'll see if I can fix it up and do the PR...
