### ISSUE TITLE
Zip:File.foreach on Excel workbook not iterating on worksheets in correct order

### ISSUE THREAD

**Issue by tikitikifoofoo** [rubyzip/rubyzip#208]
I'm using the `roo` gem to parse spreadsheet files, but I'm running into an issue with the `Zip::File.foreach` method where the order of the worksheets in the workbook is not the same as the order in which the `foreach` method iterates on the entries for those worksheets.

So to elaborate, my Excel workbook has 7 worksheets: `["IS", "BS", "CF", "WC", "DA", "DI", "EQ"]` in that order. The `roo` gem uses the `Zip::File.foreach` method to iterate over the entries in the file (see here starting on line 491: https://github.com/roo-rb/roo/blob/master/lib/roo/excelx.rb). 

But what I'm finding is that the entry for `xl/worksheets/sheet1.xml` is not actually the first sheet in the workbook (which should be the "IS" worksheet). Sometimes it's the "EQ" sheet and other times it's the "CF" sheet, so I have no idea what's going on. Any ideas why this would be happening?

The XML worksheet has nothing to identify it from the other XML worksheets in the workbook, so I'm having a really hard time solving this one.

**Comment by tamc** [comment]
I think this is an issue with Excel. I think Excel writes out the worksheets in the order they were created, NOT the order that the user sees them.

**Comment by simonoff** [comment]
Fixed in roo.
