### ISSUE TITLE
Fsync on zip file

### ISSUE THREAD

**Issue by jume-dev** [rubyzip/rubyzip#212]
Hi
I have a distributed system with multiple ruby processes. 1 of them creates a zipfile and sends a message after he is done. Another process checks if the file exists and sends a message to the user.
The problem which can occur is, that the file is still in the cache of ruby or even of the os.
Normally we have `fsync` for such kind of problems, but i can't seem to get the file, to call fsync on it. How does one do it?
Greetings,
jume

**Comment by simonoff** [comment]
Hm... why not send message from process1 to process2 what zip file created? In this case you will not care about file in cache or not.
And if you want to fsync why not doing it in first process?

**Comment by jume-dev** [comment]
Yeah, thats the point. Sorry, if i was telling it wrongly.
I want to fsync in the first process, but i don't know how. My code looks like this:
```ruby
Zip::File.open(zip_file_name, Zip::File::CREATE) do |zipfile|
  files_to_zip.each do |file|
    zipfile.add(file.sub("#{directory}/", ''), file)
  end
end
```

**Comment by simonoff** [comment]
Read http://stackoverflow.com/questions/6701103/understanding-ruby-and-os-i-o-buffering

**Comment by jume-dev** [comment]
I read that already and i know, that i need to to.
`anything.fsync`
but its the anything, i have struggle with. I can't get the right one from rubyzip.

**Comment by simonoff** [comment]
```rb
Zip::File.open(zip_file_name, Zip::File::CREATE) do |zipfile|
  files_to_zip.each do |file|
    zipfile.add(file.sub("#{directory}/", ''), file)
  end
end
f = ::File.open(zip_file_name, 'rb')
f.fsync
``

**Comment by jume-dev** [comment]
I had something similar before: `f = ::File.new(zip_file_name)
f.fsync` but this didn't work. Should be the same, if i am not mistaken.
Sometimes it did work, but sometimes i got: Errno::ENOENT: No such file or directory

**Comment by simonoff** [comment]
The only what i can say you it;s look on `on_success_replace` method in ::Zip::File.
The logic is create tmp file and after replace/move this tmp file into zip file name.
