### ISSUE TITLE
Tempfile directory when writing to buffer

### ISSUE THREAD

**Issue by oneiros** [rubyzip/rubyzip#214]
I ran into a small problem recently: Apparently, when writing to a buffer, rubyzip creates Tempfiles in the working directory. In my case, no files can be written to that directory.

My current workaround is to use `Dir.chdir` to change the working directory before using rubyzip and then set if back to the old value afterwards. This works fine, but still I wonder if a configuration option within rubyzip to set a temporary directory (maybe defaulting to `/tmp`) would make sense.

Anyway, that is just a suggestion. Keep up the good work!

**Comment by graugans** [comment]
Maybe it is an good idea to use [tempfile](http://ruby-doc.org/stdlib-2.0.0/libdoc/tempfile/rdoc/Tempfile.html) class in rubyzip for storing this kind of files

**Comment by hainesr** [comment]
Fixed. I think.
