### ISSUE TITLE
Please publish a gem version update

### ISSUE THREAD

**Issue by dogweather** [rubyzip/rubyzip#215]
The rubyzip gem was last packaged in July, 2014. There are many fixes and contributions that cannot be used by other gem authors because a gemspec dependency doesn't support git links. This is the situation I find myself in.

Application coders will still have problems, although they can workaround this by specifying a link to a commit in their gemfile. Finally, an additional problem is that the current Readme describes options and functionality not available in the most recently released gem.

Thank you.

**Comment by simonoff** [comment]
@dogweather done.

**Comment by dogweather** [comment]
Awesome! Thank you.
