### ISSUE TITLE
Getting dos_equals error "undefined method `dos_equals' for nil:NilClass (NoMethodError)"

### ISSUE THREAD

**Issue by mcmug8** [rubyzip/rubyzip#216]
Any idea, how I can by pass this error? I am getting this when running the calabash-android.

Thanks,

C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/entry.rb:470:in `=
=': undefined method`dos_equals' for nil:NilClass (NoMethodError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/entry
_set.rb:61:in `=='
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/entry
_set.rb:61:in`=='
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:334:in `!='
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:334:in`commit_required?'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:300:in `commit'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:325:in`close'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:101:in `open'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubyzip-1.1.6/lib/zip/file.
rb:138:in`foreach'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/lib/
calabash-android/helpers.rb:140:in `block (2 levels) in fingerprint_from_apk'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/lib/
calabash-android/helpers.rb:137:in`chdir'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/lib/
calabash-android/helpers.rb:137:in `block in fingerprint_from_apk'
        from C:/Ruby200-x64/lib/ruby/2.0.0/tmpdir.rb:88:in`mktmpdir'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.5/lib/

**Comment by simlw** [comment]
I encountered  the same question，any solution？

**Comment by pond** [comment]
Bump on this. It's still a "thing" in Nov 2020.
