### ISSUE TITLE
Bug: Error message goes to stdout not stderr

### ISSUE THREAD

**Issue by dogweather** [rubyzip/rubyzip#218]
"Invalid date/time in zip entry" is emitted using a simple `puts`:

https://github.com/rubyzip/rubyzip/blob/9e7af06a0b2391812f9e49e5030a3c3ff0401b9d/lib/zip/entry.rb#L574

This causes a problem with scripts which redirect their output. It causes error messages to get mixed in with the actual output. E.g.:

```bash
$ ruby test.rb > output.txt
$ head output.txt
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
```

I can submit a pull request if there's interest in a fix.

**Comment by simonoff** [comment]
You can disable it by `::Zip.warn_invalid_date`

**Comment by simonoff** [comment]
In some zip date of files stored in incorrect format. You can hide warning about it by using:

Zip.warn_invalid_date = false

**Comment by dogweather** [comment]
Thanks, I know about those options. Error messages shouldn't go to stdout, though. They should go to stderr.

**Comment by dogweather** [comment]
(Or, to a system logging library.)

**Comment by simonoff** [comment]
@dogweather if you want you can create a PR what will push it into stderr then.

**Comment by dogweather** [comment]
Great, thanks.
