### ISSUE TITLE
Zipping unix executable files changes their permissions.

### ISSUE THREAD

**Issue by cristianfraser** [rubyzip/rubyzip#220]
I have this folder

```
-rw-r--r--  1 cristian  staff  10485568 Feb  8 17:45 icudtl.dat
-rwxr-xr-x  1 cristian  staff   4678264 Feb  8 17:45 libffmpegsumo.so
-rw-r--r--  1 cristian  staff   5770126 Feb  8 17:45 nw.pak
-rwxr-xr-x  1 cristian  staff  74418984 Feb  8 17:45 app
```

Both `libffmpegsumo.so` and `app` are executable files. When I rubyzip them and unzip them I get:

```
-rw-r--r--  1 cristian  staff  10485568 Feb  8 17:49 icudtl.dat
-rw-r--r--  1 cristian  staff   4678264 Feb  8 17:49 libffmpegsumo.so
-rw-r--r--  1 cristian  staff   5770126 Feb  8 17:49 nw.pak
-rw-r--r--  1 cristian  staff  74418984 Feb  8 17:49 app
```

Is this the intended behaviour? What can I do to fix this.

I'm running OS X Yosemite 10.10.1 and using the example on the readme which has `File.open(diskFilePath, "rb")`.

**Comment by Startouf** [comment]
It's even worse for me. permissions are changed from 664 to 600...

**Comment by jonfer** [comment]
I have the same problem as @Startouf, found any solution?

**Comment by simonoff** [comment]
When you open zip file or create you need to set `restore_permissions` option to true

**Comment by simonoff** [comment]
Aha... Sorry. You need to set `entry.restore_permissions = true` to restore permissions.

**Comment by jonfer** [comment]
Thanks simonoff!

**Comment by Startouf** [comment]
In case you use `mkdir` or `chmod` to change permissions, be aware of the Unix mask than may prevent some permissions from being changed. More details [here](http://stackoverflow.com/questions/31222641/rails-mkdir-permissions-not-working-well)

I believe this ticket can be closed with jonfer's answer added to the main readme ?

**Comment by simonoff** [comment]
Waiting on PR then

**Comment by joesiewert** [comment]
I'm running into this same problem.  Is there a way to set permissions when using OutputStream?

For example, is there a way to set permissions here:
```ruby
file_stream = Zip::OutputStream.write_buffer do |zip|
  zip.put_next_entry "my_test_file.txt"
  zip.write "Just testing"
end
```

**Comment by simonoff** [comment]
@joesiewert nope. OutputStream it's internal engine, so if you using it - then use `File.chmod`

**Comment by hainesr** [comment]
Restoring permissions should now be the default, and should also be the default for the streams.
