### ISSUE TITLE
Extract an APPX File

### ISSUE THREAD

**Issue by jeremybdk** [rubyzip/rubyzip#223]
Hello,

I am trying to extract an windows phone app, the extension is .appx.

I can extract the file on my mac with 7z but when I try to do it in Ruby with rubyzip some files are correctly extracted (like the manifest in xml) but the icons are not extracted correctly (file size is 0)

How can I debug that ? is there anything I should be aware of ?

Thanks a lot for your help,

**Comment by simonoff** [comment]
How you extracting it? can you post the code?

**Comment by jaybbb** [comment]
Here is our code used to extract the file : 

     def self.extract_files_from_zip(zip_path, regex, downcase=false, exclusion=nil)
    working_dir = "#{zip_path}_folder"
    if File.exists?(working_dir)
      FileUtils.remove_dir(working_dir,true)
    end
    Dir.mkdir(working_dir)
    Zip::File.open(zip_path) do |zip_file|
      zip_file.each do |f|
        if f.name.match(regex) && (exclusion.nil? || !f.name.match(exclusion))
          working_file_path =  "#{working_dir}/#{f.name.gsub(/.*\//, '')}"
          working_file_path = working_file_path.downcase if downcase
          FileUtils.mkdir_p(File.dirname(working_file_path))
          f.extract(working_file_path)
        end
      end
    end
    return working_dir
  end

Only the png file are not extracted correctly for xap or appx files (windows applications) I used rubyzip to extract IPA and everything is fine.

Thanks for your help

**Comment by jaybbb** [comment]
@simonoff Hello, did you have time to look at it ?

Thanks a lot,

**Comment by simonoff** [comment]
@jaybbb yeah, would be great to get this XAP file. Is it for all XPA files or for your specific?

**Comment by jaybbb** [comment]
It's for all the XAP and APPX files, all the files are correctly extracted except the png files. With ZipRuby XAP extraction was working correctly with png, but not APPX.

Here is a link to a xap files : 

https://www.dropbox.com/s/pg3fd0w7k20y7tk/PanoramaApp_sign2014.xap?dl=0

Thanks a lot

**Comment by maxxfly** [comment]
I have the same issue.
For me, the issue is 
in my APPX, the PNG files are in "extracting" mode when I use zip CLI for decompress, and other files are in "inflating" mode.
