### ISSUE TITLE
Zip::InputStream reads only first file on some zip files

### ISSUE THREAD

**Issue by lluis** [rubyzip/rubyzip#227]
Hi,
on some zip files Zip::InputStream reads only the first file:

    require 'zip'
    
    Zip::File.open('b.zip') do |io|
      io.each do |entry|
        puts "Entry: #{entry.name}"
      end
    end
    
    # output:
    # Entry: 1_factura_14277089822133838.pdf
    # Entry: B632761741427708982713.pdf
    # Entry: factura_14277089822133838.xsig
    # Entry: RespuestaWS.xml
    
    Zip::InputStream.open(StringIO.new(File.read('b.zip'))) do |io|
      while (entry = io.get_next_entry)
        puts "Entry: #{entry.name}"
      end
    end
    
    # output:
    # Entry: 1_factura_14277089822133838.pdf

here is the zip example:

https://gist.github.com/lluis/bed8caa5cbccc58d47ac/raw/cb9b4db0289c0018542df72148e752f8dd13aa77/b.zip

**Comment by simonoff** [comment]
@lluis please read this https://github.com/rubyzip/rubyzip#notice-about-zipinputstream

**Comment by lluis** [comment]
@simonoff ok! but no exception is raised

**Comment by simonoff** [comment]
Exceptions implemented in master branch

**Comment by lluis** [comment]
ok thanks!
