### ISSUE TITLE
Faulty zips since ruby 2

### ISSUE THREAD

**Issue by justnorris** [rubyzip/rubyzip#232]
I was using Ruby 1.9.3 and this code, which has worked for me flawlessly for over a year:
~~~
   def self.zip(dir, zip_dir, remove_after = false)
        Zip::ZipFile.open(zip_dir, Zip::ZipFile::CREATE) do |zipfile|
            Find.find(dir) do |path|
                Find.prune if File.basename(path)[0] == ?.
                dest = /#{dir}\/(\w.*)/.match(path)
                # Skip files if they exist
                begin
                    zipfile.add(dest[1], path) if dest
                rescue Zip::ZipEntryExistsError
                end
            end
        end
        FileUtils.rm_rf(dir) if remove_after
    end
~~~

As soon as I updated to Ruby 2.1.3-stable, I have faulty zips in my hands. They're handled just fine with Mac native unzip, but for example "Keka for Mac OS X" isn't able to unzip them. Lots of windows users ( who receive my zip file ) are having problems unzipping too. In many cases - the unzip succeeds, but parts of files are missing.

Any ideas ?

**Comment by simonoff** [comment]
@justnorris you using old version of rubyzip. Please use newer version.
