### ISSUE TITLE
Zip::GPFBit3Error when using rubyzip master with selenium-webdriver

### ISSUE THREAD

**Issue by woahdae** [rubyzip/rubyzip#234]
Commit https://github.com/rubyzip/rubyzip/commit/0cb838f019e5a2fd38a294cb85b5e477f5ab89d1 is likely related to the following bug.

I'm using HEAD for the case insensitivity feature, but ran in to a problem with selenium. Could you help me understand where to dig next?

The trace is:

     Zip::GPFBit3Error: General purpose flag Bit 3 is set so not possible to get proper info from local header.Please use ::Zip::File instead of ::Zip::InputStream

    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/input_stream.rb:134:in `open_entry'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/input_stream.rb:68:in `get_next_entry'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/entry.rb:499:in `get_input_stream'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/entry.rb:583:in `block in create_file'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/entry.rb:582:in `open'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/entry.rb:582:in `create_file'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/entry.rb:154:in `extract'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/file.rb:301:in `extract'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/zipper.rb:27:in `block (2 levels) in unzip'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/entry_set.rb:42:in `call'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/entry_set.rb:42:in `block in each'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/entry_set.rb:41:in `each'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/entry_set.rb:41:in `each'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/central_directory.rb:182:in `each'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/zipper.rb:22:in `block in unzip'
    ./vendor/ruby/2.1.0/bundler/gems/rubyzip-e1d5012f8973/lib/zip/file.rb:99:in `open'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/zipper.rb:21:in `unzip'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/extension.rb:38:in `create_root'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/extension.rb:17:in `write_to'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/profile.rb:194:in `block in install_extensions'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/profile.rb:192:in `each'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/profile.rb:192:in `install_extensions'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/profile.rb:76:in `layout_on_disk'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/launcher.rb:58:in `create_profile'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/launcher.rb:34:in `block in launch'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/socket_lock.rb:20:in `locked'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/launcher.rb:32:in `launch'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/bridge.rb:24:in `initialize'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/driver.rb:31:in `new'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/driver.rb:31:in `for'
    ./vendor/ruby/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver.rb:67:in `for'
    ./vendor/ruby/2.1.0/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:13:in `browser'
    ./vendor/ruby/2.1.0/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:45:in `visit'
    ./vendor/ruby/2.1.0/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
    ./vendor/ruby/2.1.0/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
    ./vendor/ruby/2.1.0/gems/rspec-rails-3.1.0/lib/rspec/rails/example/feature_example_group.rb:28:in `visit'
    ./spec/acceptance/acceptance_helper.rb:18:in `log_in'
    ...

The trace points to line 27 of `selenium-webdriver-2.45.0/lib/selenium/webdriver/common/zipper.rb`, which on github is line 44 due to the comment header:

https://github.com/SeleniumHQ/selenium/blob/51fd82ec9cb1ebe7596bf7bb3fb8290113466a9a/rb/lib/selenium/webdriver/common/zipper.rb#L44

Selenium is using `Zip::File.open` and subsequently `zip.extract(entry, to)`, and rubyzip is internally calling `Zip::InputStream#open_entry` and encountering this failure.

Is it obvious what's happening, or do I need to create a repro project?

**Comment by woahdae** [comment]
Can confirm, reverting 0cb838f as seen [in my fork of master](https://github.com/woahdae/rubyzip) allows selenium to boot.

**Comment by simonoff** [comment]
@woahdae Yeah, it's broken now. I'm working now on big fix. Need to rewritten logic how local file header and central directory parsed.

**Comment by simonoff** [comment]
@woahdae can you test it again? I realized what for proper fix need to rewrite a lot of code. So I made such quick fix.

**Comment by jufemaiz** [comment]
I'm getting this on a file received from a third party via email. Raise a distinct issue?

**Comment by apanzerj** [comment]
If you want to know more about General Purpose Bit 3 read here: https://github.com/adamhathcock/sharpcompress/issues/88
