### ISSUE TITLE
Mac Archive Utility will not open archives if there are identical filenames added to the zip file

### ISSUE THREAD

**Issue by FergusonSean** [rubyzip/rubyzip#240]
Just posting this here so maybe someone else doesn't have to do the wild goose chase.

Other unzip tools seem to work fine in this case, but it might be a good idea to raise an error for duplicate entries in the zip file. The behavior is somewhat weird as I'm not really sure which of the 2 files would be unzipped.

**Comment by ermacaz** [comment]
+1 what a stupid bug apple

**Comment by hainesr** [comment]
This issue was opened long ago (sorry) and default is now to reject duplicate entries. Can be overridden though.

**Comment by ilich2kode** [comment]
> This issue was opened long ago (sorry) and default is now to reject duplicate entries. Can be overridden though.

Can you tell me how this can be changed?
So that he still extracts all the files from the archive and renames the duplicates.
