### ISSUE TITLE
error when extracting zip on windows and warning when using Keka

### ISSUE THREAD

**Issue by jdkealy** [rubyzip/rubyzip#245]
Hi, 

I use a mac. I generate photo file zips for clients on a server using code that looks like this: 
    Zip::ZipFile.open(zip_path, Zip::ZipFile::CREATE) do |zipfile|
      photo_paths.each do |path|
        i  = $redis.hgetall(zip_key)
        photo_filename = path.split('/').last
        event_id       = photo_filename.split(".").first.split("_")[1]
        photo_id       = photo_filename.split(".").first.split("_").last
        photo_filename = "NAMINGCONVENTION_#{event_id}_#{photo_id}#{File.extname(path)}"
        zipfile.add(photo_filename, path)
      end
    end
    %x[chmod 0644  #{zip_path}]

On a mac using archive utility the generated zip file works great. However, when using Keka, the file opens even though it gives the error:  
Error code 2 using "p7zip"
Fatal error

Lastly on windows the file does not open at all.

**Comment by hainesr** [comment]
This looks like the old API. Have you tried using the latest version of rubyzip?

**Comment by jdkealy** [comment]
You're right. Upgraded.
