### ISSUE TITLE
README

### ISSUE THREAD

**Issue by georgeu2000** [rubyzip/rubyzip#257]
I think this line is not needed:

`zipfile.get_output_stream("myFile") { |os| os.write "myFile contains just this" }`

**Comment by hainesr** [comment]
Why isn't it needed? It's an example of how to use the `get_output_stream` call.

**Comment by mnaberez** [comment]
This line exists to show another useful method of the API.  It doesn't need to be removed.

**Comment by georgeu2000** [comment]
I was referring to **Basic zip archive creation**.

It seems that `zipfile.add(filename, folder + '/' + filename)` adds the source file to the zip file. Does `zipfile.get_output_stream("myFile") { |os| os.write "myFile contains just this" }` append to it?

**Comment by mnaberez** [comment]
> Does zipfile.get_output_stream("myFile") { |os| os.write "myFile contains just this" } append to it?

It creates a new entry in the zip archive named `myFile` and writes `myFile contains just this` as the contents.  The reason both `add` and `get_output_stream` are shown in the example is they are different ways of adding to the zip archive.  Use `add` for files on disk, use `get_output_stream` for data in memory.
