### ISSUE TITLE
Error in example_recursive.rb

### ISSUE THREAD

**Issue by p-kolacz** [rubyzip/rubyzip#260]
In `rubyzip/samples/example_recursive.rb` (https://github.com/rubyzip/rubyzip/blob/05916bf89181e1955118fd3ea059f18acac28cc8/samples/example_recursive.rb#L43)  it should be `f.write`. 'Puts' puts extra line in files, damaging them.

**Comment by pol0nium** [comment]
+1

It damaged xlsx files when zipping them. I replaced the `puts` with a `write` and the file corruption disappeared.

**Comment by hainesr** [comment]
Thanks for catching and confirming. Could you submit a PR?

**Comment by pol0nium** [comment]
Done.

This may be a fix for https://github.com/rubyzip/rubyzip#modify-docx-file-with-rubyzip too ?

**Comment by emiddleton** [comment]
The example in the README.md still uses puts.

**Comment by jdleesmiller** [comment]
It looks like this was fixed in #297.

And it looks like the README was fixed in #283 .
