### ISSUE TITLE
Release new version to rubygems

### ISSUE THREAD

**Issue by henders** [rubyzip/rubyzip#262]
Last version 1.1.7 created on Feb 2nd 2015.

Can you update with the latest changes please.  I'd like to get the fix from PR https://github.com/rubyzip/rubyzip/pull/250.

Thanks!

**Comment by pbennett** [comment]
Yes please!!!
We've run into this as well and it's pretty crippling.

**Comment by Paxa** [comment]
+1

**Comment by simonoff** [comment]
After new year only. Sorry on vacation now.

**Comment by flower-pot** [comment]
Yes would be really nice and much appreciated. :)

**Comment by mbrunat** [comment]
One vote from me too. Thank you

**Comment by creddy** [comment]
I apologize for the noise. It'd be nice to see a new version out on rubygems. Thanks!

**Comment by foobear** [comment]
+1

**Comment by creddy** [comment]
Thank you! Version 1.2.0 is now on rubygems.org https://rubygems.org/gems/rubyzip/versions/1.2.0

**Comment by henders** [comment]
Great! Thanks!
