### ISSUE TITLE
Missing files when decompressing *invalid* archives (more than 64k files)

### ISSUE THREAD

**Issue by default50** [rubyzip/rubyzip#266]
This file [codedeploy-test.zip](https://github.com/rubyzip/rubyzip/files/77048/codedeploy-test.zip) was produced by a default installation of Jenkins ver. 1.625.3 on Ubuntu 14.04.

On a standard Ubuntu 12.04:

> $ unzip -l codedeploy-test.zip
> Archive:  codedeploy-test.zip
> Length      Date    Time    Name
> ---
> 
>    10884  2016-01-01 23:38   codedeploy-test/LICENSE.txt
> ...
>     2002  2016-01-01 23:38   codedeploy-test/scripts/unprotect_asg.sh
> ---
> 
>   460880                     70016 files
> 
> $ unzip -v
> UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

So unzip from Info-ZIP gets the **right** amount of files (70016). However, if you do:

> $ zip -T codedeploy-test.zip 
>   zip warning: expected 4480 entries but found 70016
> zip error: Zip file structure invalid (codedeploy-test.zip)

According to [Info-ZIP FAQ](http://www.info-zip.org/FAQ.html#limits) the limit of 64k files exists, but it is overcome in UnZip 5.41 (16 Apr 2000). Many other unarchivers for Linux and Mac that I've tested don't have issues with that file in spite of the _invalid_ file structure.

If you run [this script](https://gist.github.com/default50/8dda2ef37dfb22c00e38#file-rubyzip_test-rb) that only counts the numbers of files to be decompressed:

> $ ruby rubyzip_test.rb codedeploy-test.zip
> Processing file codedeploy-test.zip:
> rubyzip counted 4480 files.

That was using **rubyzip 1.1.7**.  This is causing issues because files are missing on target as you can imagine. If you think supporting this type of invalid files is not correct, at least it would be great to error out when detecting them, so that the user doesn't think that everything is fine.

I believe this _may_ be related to issue #247.

Thanks!

**Extra info**

If I _fix_ the file ([codedeploy-test-fixed.zip](https://github.com/rubyzip/rubyzip/files/77047/codedeploy-test-fixed.zip)) by doing:

> $ zip -FF codedeploy-test.zip --out codedeploy-test-fixed.zip
> $ zip -T codedeploy-test-fixed.zip
> test of codedeploy-test-fixed.zip OK

Then:

> $ ruby rubyzip_test.rb codedeploy-test-fixed.zip 
> Processing file codedeploy-test-fixed.zip:
> rubyzip counted 70016 files.

**Comment by hainesr** [comment]
I had a look at the attached zip file (thanks!) but in the actual End of Central Directory Record it states there are 4480 files. So that's all we have to go on. If we then went and attempted to extract any more files than that we'd be susceptible to all sorts of attacks and rubyzip could be used to stealthily install files "hidden" in a well crafted zip without any protections.

Isn't the issue here that whatever CodeDeploy is is creating broken zips and needs to be fixed? I realise that this issue is a few years old, so maybe it has?

**Comment by hainesr** [comment]
I'm going to close this because Rubyzip is (I think) doing the right thing here and only accessing the number of files that the EoCD record states are present in the archive.
