### ISSUE TITLE
Read zip example in readme.md - undefined local variable or method `dest_file' for main:Object (NameError)

### ISSUE THREAD

**Issue by danrfhughes** [rubyzip/rubyzip#271]
Implementing the example code in ready.md, I get the error above. It could be simply that the realm is not clear. The code I've implemented - 

```
require 'rubygems'
require 'zip'

Zip::File.open('test.epub') do |zip_file|
  # Handle entries one by one
  zip_file.each do |entry|
    # Extract to file/directory/symlink
    puts "Extracting #{entry.name}"
    entry.extract(dest_file)

    # Read into memory
    content = entry.get_input_stream.read
  end
end
```

Have I understood this incorrectly? Thanks.

**Comment by fffdan** [comment]
So I did misunderstand that. Would it to be worth updating the readme to say `entry.extract(#{entry.name})` ? Happy to make pull request if that is suitable.

**Comment by hainesr** [comment]
It should be just `entry.extract` and it seems the README was updated - probably a while ago! 😄
