### ISSUE TITLE
Please describe 1.2.0 in the changelog

### ISSUE THREAD

**Issue by jaredbeck** [rubyzip/rubyzip#275]
Thanks, it's scary to upgrade without knowing what changed. :)

**Comment by simonoff** [comment]
:)))

**Comment by simonoff** [comment]
Done

**Comment by jaredbeck** [comment]
> Done

I don't see 1.2.0 in https://github.com/rubyzip/rubyzip/blob/master/Changelog.md.  What am I missing? Thanks.

**Comment by simonoff** [comment]
In release notes yet

Надіслано з iPhone

21 лют. 2016 р. о 19:56 Jared Beck <notifications@github.com> написав(ла):

**Comment by jaredbeck** [comment]
I see. If you are going to use https://github.com/rubyzip/rubyzip/releases instead of https://github.com/rubyzip/rubyzip/blob/master/Changelog.md then I recommend deleting https://github.com/rubyzip/rubyzip/blob/master/Changelog.md.  Thanks
