### ISSUE TITLE
Zip file corruption with password protected in MS Windows 64bit and workarround way

### ISSUE THREAD

**Issue by samtptw** [rubyzip/rubyzip#279]
My condiction is 
my gem env.
RubyGems Environment:
- RUBYGEMS VERSION: 2.4.5.1
- RUBY VERSION: 2.2.4 (2015-12-16 patchlevel 230) [x64-mingw32]
- INSTALLATION DIRECTORY: C:/Ruby22-x64/lib/ruby/gems/2.2.0
- RUBY EXECUTABLE: C:/Ruby22-x64/bin/ruby.exe
- EXECUTABLE DIRECTORY: C:/Ruby22-x64/bin
- SPEC CACHE DIRECTORY: C:/Users/jsheen/.gem/specs
- SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
- RUBYGEMS PLATFORMS:
  - ruby
  - x64-mingw32
- GEM PATHS:
  - C:/Ruby22-x64/lib/ruby/gems/2.2.0
  - C:/Users/jsheen/.gem/ruby/2.2.0
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - https://rubygems.org/
- SHELL PATH:
  - C:\Ruby22-x64\bin
  - C:\ProgramData\Oracle\Java\javapath
  - C:\Windows\system32
  - C:\Windows
  - C:\Windows\System32\Wbem
  - C:\Windows\System32\WindowsPowerShell\v1.0\
  - C:\Program Files\nodejs\
  - C:\Program Files\TortoiseGit\bin
  - C:\Users\jsheen\AppData\Roaming\npm
  - C:\Ruby22-x64\devkit\bin

OS: MS Windows7 64bit
Rubyzip: rubyzip (1.2.0)

Symptom:
The Zip file has been created has corrupted sometimes. The corrupted zip file can not be open.
# 
# Zip end encript content

```
buffer = Zip::OutputStream.write_buffer(::StringIO.new(''), Zip::TraditionalEncrypter.new(gpwd)) do |zip|           
  zip.put_next_entry(input_filename)                             #setting zip entry
  zip.print File.read(FOLDER+input_filename)              #read file to Stream
end.string 
```
# Zip file create

File.open(zip_filename,"w:UTF-8") do |outfile|                 #zip file create by Stream 
    outfile.print(buffer)
end
# 

Workaround Way: 
To change read and write to binary mode.

---
# Zip 加密在抓到的CSV檔

```
buffer = Zip::OutputStream.write_buffer(::StringIO.new(''), Zip::TraditionalEncrypter.new(gpwd)) do |zip|           
  zip.put_next_entry(input_filename)                               #設定 Zip中的內容
  zip.print **IO.binread(FOLDER+input_filename)**           
```

 #讀取檔案及寫入進 Stream should change binary mode to read file in MS Window 
    end.string    
# Zip檔案產生

File.open(zip_filename,"w**b**:UTF-8") do |outfile|  
 #zip file由Stream 產生 should change binary mode to write file in MS Window
    outfile.print(buffer)
 end

---

Rubyzip create zip file in not binary mode will always corruption with password protected in MS Windows. This should be an issue.

```
                                                     Sam Sheen
```

**Comment by jspanjers** [comment]
When you write binary data to a file using File.open, on MS Windows you should always specify 'wb'.
That is the way File.open works, I do not think that is an issue, nor that it is an issue within rubyzip.

Within rubyzip, you should use Zip::OutputStream.open(zip_filename, Zip::TraditionalEncrypter.new('password') ) to create an encrypted zip file. This handles writing to the file in binary mode automatically.

I think this issue can be closed.
