### ISSUE TITLE
rubyzip 1.2.0 could not extract zip file from xxx/*.xxx source

### ISSUE THREAD

**Issue by tempwall** [rubyzip/rubyzip#281]
rubyzip: 1.2.0
detail: zipped file with command like "zip -r kw_cn.zip kw_cn/*.csv" could not be unzipped by rubyzip.
contrast:  command "unzip" works well
analysis: there is no directory node in this type of zip file, versus the command like "zip -r kw_cn.zip kw_cn"
comment: we could only use shell command instead, waiting for your update.

**Comment by hainesr** [comment]
I can't replicate this on Ubuntu 14.04.

I tried `zip -r test.zip samples/*.rb` in the root directory of the rubyzip source, then in `irb`:

```
zf = Zip::File.new('test.zip')
zf.read('samples/qtzip.rb')
```

And it worked fine.

Am I missing something? How did you attempt to extract the files? What error did you get? Could you attach an example zip file that doesn't work?
