### ISSUE TITLE
Possible to list archive files? 

### ISSUE THREAD

**Issue by ingolfured** [rubyzip/rubyzip#282]
Is is possible to list all files in a zip without unzipping everything? Similar to the `unzip -l` option.

**Comment by mnaberez** [comment]
$ mkdir foo
    $ touch foo/bar
    $ touch foo/baz
    $ zip -r foo.zip foo
      adding: foo/ (stored 0%)
      adding: foo/bar (stored 0%)
      adding: foo/baz (stored 0%)
    $ unzip -l foo.zip
    Archive:  foo.zip
      Length     Date   Time    Name
     --------    ----   ----    ----
            0  03-17-16 16:21   foo/
            0  03-17-16 16:21   foo/bar
            0  03-17-16 16:21   foo/baz
     --------                   -------
            0                   3 files
    $ irb
    irb> require 'rubygems'; require 'zip'
    => true
    irb(main):003:0> names = Zip::File.open("foo.zip") { |zf| zf.entries.map(&:name) }
    => ["foo/", "foo/bar", "foo/baz"]
    
Each entry returned by `zip.entries` is a [`Zip::Entry`](https://github.com/rubyzip/rubyzip/blob/v1.2.0/lib/zip/entry.rb).
