### ISSUE TITLE
Cyrillic character in folder name is decompressing to non-unicode character

### ISSUE THREAD

**Issue by jpatters** [rubyzip/rubyzip#293]
I have a file in a zip with the character Д in a folder name. It is decompressing to a non-unicode character (being rendered as a ?) in Ubuntu. In OSX it is decompressing to %84.
In Ubuntu, the `unzip` package handles this properly. In OSX the default unzip package (not sure what it is called) renders it as a Ñ.
The non-unicode character is causing issues when trying to re-zip the directory.
I have `Zip.unicode_names = true` set for both the unzip and zip process.

Any help would be appreciated.

**Comment by hainesr** [comment]
Could you attach an example zip file please?

**Comment by mojavelinux** [comment]
I'm seeing the same result. If you run the test in https://github.com/rubyzip/rubyzip/blob/master/test/unicode_file_names_and_comments_test.rb but disable unlinking the test file, you'll see that if you open it, all the unicode characters are replaced with ?. I'm seeing this on a Fedora 21 box. So while the test passes, it's not actually working.

**Comment by mojavelinux** [comment]
If I open the file with a text editor, I do see the the unicode names in the character stream. So the information is definitely in there. It just doesn't seem that any zip/unzip program I try can see them.

**Comment by mojavelinux** [comment]
Actually, this appears to be a viewer issue. If I use unzip to extract the archive from the test, then it properly writes all the files using the correct names. So maybe this isn't a bug after all (and the test really does work).

**Comment by jpatters** [comment]
Totally forgot I submitted this.
This was a viewer issue. I told ssh not to forward my locale information and was able to see all characters correctly.
