### ISSUE TITLE
Set correct file permissions given a umask of 0027

### ISSUE THREAD

**Issue by metavida** [rubyzip/rubyzip#294]
We lock down our umask to 0027 so that files are not globally readable. When creating files via `File.open` this results in files with permissions of 0640 (i.e. `rw-r----`) but zip files created with this library end up with the very odd permission of 0637 (e.g. `rw--wxrwx`).

[I've added a failing test case to `test/file_permissions_test.rb`](https://github.com/rubyzip/rubyzip/compare/7aa3666e341b4ecf3b66321d734802a77bba962b...metavida:umask-0027) on my branch but haven't had time to actually write a solution nor to do any testing on windows.

**Comment by metavida** [comment]
Note, I believe bug exists because the permission calculation introduced in Pull #237 relies on direct subtraction (0666 - 0027 = 0637) and in reality linux must not actually use direct subtraction internally.

**Comment by hainesr** [comment]
I've had a go at fixing this in #300. Can people comment on whether how I've fixed it is sensible?
