### ISSUE TITLE
example_recursive will lost some special characters

### ISSUE THREAD

**Issue by EagleSHCN** [rubyzip/rubyzip#296]
I've run the example_recursive with some binary files , but after extract I found some files will lost special characters ( for example 0x1a is lost at file end ) .

  Modify 
`def put_into_archive(disk_file_path, io, zip_file_path)
    io.get_output_stream(zip_file_path) do |f|
      f.write(File.open(disk_file_path, 'rb').read)
    end
  end`

   to
`def put_into_archive(disk_file_path, io, zip_file_path)
    io.add(zip_file_path, disk_file_path)
  end`

  could fix this issue .

**Comment by jdleesmiller** [comment]
It looks like this was fixed in #297, so I'll close out the issue.
