### ISSUE TITLE
ZipInputStream broken

### ISSUE THREAD

**Issue by tillvollmer** [rubyzip/rubyzip#30]
The following code only shows the first real file in the attached zip. The rest is not shown anymore.
Zip file created on Mac OSX.

 Zip::ZipInputStream::open("eins.zip") do  |io|
          while (entry = io.get_next_entry)
            pp entry
           end
end

old zip files work.

but 

Zip::ZipFile::foreach("eins.zip") do |entry|
  pp entry.name
end

works for the same file.

**Comment by amilligan** [comment]
I just tested this in the recent 1.1.7 version, and it still does not work properly.

**Comment by cattywampus** [comment]
I also just tested this with 1.1.7 and I am only reading the first entry when I use the `Zip::InputStream#open` call. What's interesting is it works fine when I use `Zip::File#open`, however that's not ideal since the zip data is in memory and not on disk for my situation.

**Comment by vishaldeepak** [comment]
+1 Having the same issue

**Comment by jjercTK** [comment]
I have the problem too with zip files created on my mac and read with InputStream. I asked a coworker to zip the same file on a Ubuntu, and InputStream works with that zip file.
