### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by rjrobinson** [rubyzip/rubyzip#302]
Ruby 2.2.2 

I'm looking for a memory leak in my code, and Im wondering if the pattern im using is wrong. 

``` ruby
def unzip_to_json(key)
    data = ''
    @s3 ||= GruS3Bucket.new
    file_name = File.basename(key)
    @s3.download_file(file_name, key)
    Zip::File.open(file_name) do |zip_file|
        zip_file.each do |entry|
          entry.get_input_stream do |stream|
            data << stream.read
        end
    end
    data # in json
  end
```

Im curious if I need to close the file at any point?

**Comment by istana** [comment]
I don't know about memory leak in zip, but you assign file from s3 to `@s3` instance variable which survive until the end of an instance of the object, not the end of `unzip_to_json` method, so it can take a lot of memory.
