### ISSUE TITLE
File permissions are lost on a recursive create

### ISSUE THREAD

**Issue by tigris** [rubyzip/rubyzip#305]
I was using the `sample` to create a recursive zip file. But all created files in the resulting zip file have permissions of 0644 on linux. It would be could if the source file permissions were kept, so that this sample class was an exact replicate of doing a system call to `zip dest.zip src_dir`, on systems that aren't lucky enough to have the zip command.

**Comment by svobom57** [comment]
+1, having the same issue (version 1.2.0)

**Comment by yishuiliunian** [comment]
+1 , how to solve this ?

**Comment by simonoff** [comment]
@tigris you can set a `unix_perms` for each `Zip::Entry` object or you can add `permission` parameter to `get_output_stream` method.
