### ISSUE TITLE
Recursive Entry#glob

### ISSUE THREAD

**Issue by tiagofsilva** [rubyzip/rubyzip#310]
Is there a possibility to make `Entry#glob` look for files recursively, including files inside a zip file? Say we have a `top.zip` file that has a `nested.zip` that has a `mydoc.txt`. Doing `glob("**/*.txt")` would return `mydoc.txt`. I did that in an app I did manipulating `Zip::File` but I don't know how you feel about this implemented in the gem itself.

**Comment by hainesr** [comment]
I think this might be OK if it was something that could be specifically switched on, say with a `recursive: true` parameter to `Entry#glob`. I'd be worried about security aspects though - would it be possible to craft a `nested.zip` that referenced itself for an infinite loop? Also, did you just want to know if a particular file was in there somewhere, or did you then want to be able to get access to it directly? I'm wondering how you'd manage the nested `ZipInputStream`s, for example...

I've just noticed that you submitted this about 4.5 years ago, sorry!

**Comment by hainesr** [comment]
Going to close this now. Happy to have a proposal for this sort of functionality but I think it should be off by default, and maybe have a limit on depth?
