### ISSUE TITLE
uninitialized constant File::FNM_EXTGLOB since latest release 1.2.1 with Ruby 1.9

### ISSUE THREAD

**Issue by joerg** [rubyzip/rubyzip#317]
Hi,

We are getting an error when using glob from a zipfile with the latest release 1.2.1. Here is how to reproduce the error:

```
# cd /tmp
# touch test.txt
# zip test.zip test.txt
  adding: test.txt (stored 0%)
# zipinfo test.zip
Archive:  test.zip
Zip file size: 166 bytes, number of entries: 1
-rw-r--r--  3.0 unx        0 bx stor 17-Feb-09 11:58 test.txt
1 file, 0 bytes uncompressed, 0 bytes compressed:  0.0%

# jruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.6.0_45-b06 +jit [linux-amd64]
# jirb -v
irb 0.9.6(09/06/30)
# jirb 
```
And there call:
```
require 'zip'

Zip::File.open('test.zip', nil) { |zipfile|
    zipfile.glob('test.txt')
}
```

The error is:
```
NameError: uninitialized constant File::FNM_EXTGLOB
        from org/jruby/RubyModule.java:2726:in `const_missing'
        from /opt/jruby-1.7.19/lib/ruby/gems/shared/gems/rubyzip-1.2.1/lib/zip/file.rb:354:in `glob'
        from (irb):16:in `evaluate'
        from /opt/jruby-1.7.19/lib/ruby/gems/shared/gems/rubyzip-1.2.1/lib/zip/file.rb:101:in `open'
        from (irb):15:in `evaluate'
        from org/jruby/RubyKernel.java:1107:in `eval'
        from org/jruby/RubyKernel.java:1507:in `loop'
        from org/jruby/RubyKernel.java:1270:in `catch'
        from org/jruby/RubyKernel.java:1270:in `catch'
        from /opt/jruby-1.7/bin/jirb:13:in `(root)'
```

Using Ruby 2.3 the same test works, using Ruby 1.9.3 I do get the same error (both not JRubies). My guess is that renaming the Class to File from ZipFile gives resolution errors.

**Comment by stevenday** [comment]
I'm seeing this too. https://github.com/rails/rails/commit/35864db96132a820ce1c4a67dbac5e656a5b8489 seems like it might help? Apparently `FNM_EXTGLOB` was introduced in Ruby 2.0

**Comment by simonoff** [comment]
@stevenday yep.

**Comment by deivid-rodriguez** [comment]
I introduced the change and I didn't know it didn't work in Ruby 1.9... CI didn't catch it either because 1.9 support is supposed to have been dropped.

This comment describes the situation perfectly: https://github.com/rubyzip/rubyzip/pull/256#issuecomment-155850817.

**Comment by jdleesmiller** [comment]
While dropping 1.9 support could have been smoother, I don't think we're likely to re-introduce it now, because 1.9 has been end of life [since 2015](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/), so I'll close this out.
