### ISSUE TITLE
OutOfMemoryError on JRuby

### ISSUE THREAD

**Issue by petr-tichy** [rubyzip/rubyzip#322]
Running the following test on `JRuby` versions `1.7.25`, `9.1.5.0` and `9.1.9.0-SNAPSHOT` results in `java.lang.OutOfMemoryError: Java heap space`. On MRI Ruby this works OK.

```
require 'zip'

data = Random.new.bytes(2**20)

Zip::File.open('archive.zip', Zip::File::CREATE) do |zipfile|
  zipfile.get_output_stream("test") do |os|
    200.times do |i|
      os.write data
    end
  end
end
```

This is IMHO a JRuby bug, which I've reported in https://github.com/jruby/jruby/issues/3962

**Comment by headius** [comment]
Still seems to be an issue. Sorry for the long delay in noticing this one!

**Comment by hainesr** [comment]
Hopefully safe to close this one now. Shout if not.
