### ISSUE TITLE
Fail to add a file with a same name from another folder [Zip::EntryExistsError]

### ISSUE THREAD

**Issue by Hellfar** [rubyzip/rubyzip#323]
As I mentioned in this post:
https://stackoverflow.com/questions/43234973/rubyzip-fail-to-add-a-file-with-a-same-name-from-another-folder-zipentryexist

I cannot manage to store in a zip file two files (located in different folders) sharing the same name.

Am I doing anything wrong here ? Is there an option I am missing ? Or is this an issue ?

**Comment by simonoff** [comment]
You need to use a full path. Not basename

Надіслано з iPhone

7 квіт. 2017 р. о 18:52 Pierre Louchet <notifications@github.com> написав(ла):

**Comment by Hellfar** [comment]
Thanks to you. I changed my code and this now working fine :) !
