### ISSUE TITLE
Functionally equivalent blocks of code generate different zip files 

### ISSUE THREAD

**Issue by stadelmanma** [rubyzip/rubyzip#330]
I have ran into this issue also while working with docx files. Relevant PR comment on Sablon. https://github.com/senny/sablon/pull/54#issuecomment-302755679

The first generates an `images.docx` file that MS word can open no problem (458476 bytes total). The second block creates a "corrupted" MS Word doc with exactly the same unzipped content and is 458793 bytes total. 

Relevant branch to clone in order to reproduce the issue: https://github.com/stadelmanma/sablon/tree/ruby-zip-generates-different-docx

That block of code is in template.rb, Sablon::Template#render, beginning on line 21.

Generates valid doc
```ruby
        Sablon::Processor::Image.init!(context)
        # reading the file into a stream prevents inplace modification of file
        zip_file = IO.binread(@path)
        Zip::File.open_buffer(zip_file) do |docx_zip|
          # loop over entries inside zip file
          docx_zip.entries.each do |entry|
            entry_name = entry.name
            out.put_next_entry(entry_name)
            content = entry.get_input_stream.read
            if entry_name == 'word/document.xml'
              out.write(process(Processor::Document, content, env, properties))
            elsif entry_name =~ /word\/header\d*\.xml/ || entry_name =~ /word\/footer\d*\.xml/
              out.write(process(Processor::Document, content, env))
            elsif entry_name == 'word/numbering.xml'
              out.write(process(Processor::Numbering, content, env))
            elsif entry_name == 'word/_rels/document.xml.rels'
              out.write(process(Processor::Image, content, properties))
            elsif entry_name == '[Content_Types].xml'
              out.write(process(Processor::ContentType, content, properties, out))
            else
              out.write(content)
            end
          end
          # finally add all used images to the zip file
          env.images.add_images_to_zip!(out)
        end
      end
```

Generates corrupted doc
```ruby
        Sablon::Processor::Image.init!(context)
        # reading the file into a stream prevents inplace modification of file
        zip_file = IO.binread(@path)
        Zip::File.open_buffer(zip_file) do |docx_zip|
          # write out relationships
          entry_name = 'word/_rels/document.xml.rels'
          out.put_next_entry(entry_name)  # <-- this line causes the corruption even if I comment out the two below
          rels_file = docx_zip.find_entry(entry_name)
          content = rels_file.get_input_stream.read
          out.write(process(Processor::Image, content, properties))
          # loop over entries inside zip file
          docx_zip.entries.each do |entry|
            entry_name = entry.name
            out.put_next_entry(entry_name)
            content = entry.get_input_stream.read
            if entry_name == 'word/document.xml'
              out.write(process(Processor::Document, content, env, properties))
            elsif entry_name =~ /word\/header\d*\.xml/ || entry_name =~ /word\/footer\d*\.xml/
              out.write(process(Processor::Document, content, env))
            elsif entry_name == 'word/numbering.xml'
              out.write(process(Processor::Numbering, content, env))
            elsif entry_name == '[Content_Types].xml'
              out.write(process(Processor::ContentType, content, properties, out))
            else
              out.write(content)
            end
          end
          # finally add all used images to the zip file
          env.images.add_images_to_zip!(out)
        end
      end
```

**Comment by senny** [comment]
@stadelmanma I haven't looked into this specifically but won't the second example write the `word/_rels/document.xml.rels` twice? First before iterating over the entries and the second time in the `else` branch of the big conditional.

**Comment by stadelmanma** [comment]
@senny, you are correct, I should have put the actual write portion below the main block. In any case the document should open without error and you'll just see blank images with a little red 'X' instead of the actual content, not a corrupted document warning. 

The bigger issue I don't understand is why the line `out.put_next_entry(entry_name)`  by itself will corrupt the docx file if it is outside of the main entries do loop block. 

i.e. the bit below is all that is required to create an invalid doc with a different byte count and *nothing* is being written to the output file.
```ruby
          out.put_next_entry(entry_name)  # <-- this line causes the corruption even if I comment out the two below
          #rels_file = docx_zip.find_entry(entry_name)
          #content = rels_file.get_input_stream.read
```

**Comment by hainesr** [comment]
Hello, I noticed that you seem to have worked around the issue you describe here - and I'll be honest and admit to not knowing what the consequences of writing the `word/_rels/document.xml.rels` file twice - so I'll close this now, and if it bites again, please let us know.

Incidentally @senny and @stadelmanma I notice you are owners/committers in Sablon and you have `>= 1.3.0` in your `gemspec`. Please note that Rubyzip 3.0 is on the way and has breaking changes!
