### ISSUE TITLE
Binary files in Tempfile

### ISSUE THREAD

**Issue by cryocz** [rubyzip/rubyzip#333]
Hello,
I'm using RubyZip to merge zip files that contain binary files, and I've noticed that `Tempfile` class (when reopened) starts in `r+` mode. This causes some data loss as I've described at [this](https://stackoverflow.com/questions/45041794/ruby-tempfile-corruption-of-binary-files) stackoverflow thread. Is there an easy way around this?

Thank you

**Comment by jspanjers** [comment]
This seems to be related to #265.

**Comment by jspanjers** [comment]
Hi cryocz,

Can you give us an example of your code that uses rubyzip and cause this issue?

**Comment by cryocz** [comment]
Hey,
it's been quite some time, so I'm not entirely sure what _exactly_ was the issue I was bumping into. I believe I was having troubles modifying `.jar` files, as `rubyzip` was creating a `Tempfile`, which it then reopened using text mode, and that lead to some bytes getting trimmed.

Whatever the bug was, I don't think I will be able to replicate it, so I'm closing the issue.
