### ISSUE TITLE
Encoding::UndefinedConversionError: "\xA5" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by tansaku** [rubyzip/rubyzip#334]
I seem to be getting a strange conversion error - it's part of another gem, but it's occurring when files are unzipped.

Does anyone have any idea is rubyzip can somehow manage this kind of conversion?

here's more of the error:

```
    Then I should receive a grade of "100" for my assignment                                             # features/step_definitions/adapter_x_queue_steps.rb:49
      expected PutResultException, got #<Encoding::UndefinedConversionError: "\xA5" from ASCII-8BIT to UTF-8> with backtrace:
        # /Users/tansaku/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_submission.rb:130:in `block in unzip'
        # /Users/tansaku/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_submission.rb:130:in `unzip'
        # /Users/tansaku/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_submission.rb:80:in `block in write_to_location!'
        # /Users/tansaku/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_submission.rb:78:in `each'
        # /Users/tansaku/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_submission.rb:78:in `write_to_location!'
        # ./lib/submission/xqueue.rb:23:in `next_submission_with_assignment'
```

**Comment by jdleesmiller** [comment]
I'm afraid I don't have any specific ideas here, sorry. We'd need a more complete bug report to make progress on this, ideally with a minimum working/non-working example that shows how the zip file comes to contain an `\xA5` byte.

**Comment by LinFelix** [comment]
This is a typical error for using `entry.get_input_stream.read` instead of `entry.extract(...)` for _binary_ files.

But without the erroneous code we will never know. I made this comment because I ran into the same problem googling led me here. So maybe this will help someone in the future.

**Comment by santosgabriel** [comment]
Since I ran into the same error, I believe it worth mention one possible solution here.

`entry.get_input_stream.read` since read is a String you can call `.force_encoding("UTF-8")`

`entry.get_input_stream.read.force_encoding("UTF-8")`
