### ISSUE TITLE
View and/or preserve original date created, date modified?

### ISSUE THREAD

**Issue by goldtreefrog** [rubyzip/rubyzip#336]
For files inside the zip file, is there any way in rubyzip to access their original dates created and modified? If I extract them, Windows shows them as having been created and modified at the time of the extraction, which is quite different from the dates showing inside the zip file. I need to be able to list the dates they were originally created and last modified and, ideally, preserve those dates with the extracted files.

I have searched for this answer both here and on the Web, and the only references to solutions I can find use DotNetZip or Python. I would like to use Ruby.

Thanks.

**Comment by hainesr** [comment]
This maybe another instance of behaviour seen in #465, but also could be something that will be fixed by fixing #422. Either way, I'm looking into it (finally).
