### ISSUE TITLE
Zip::CompressionMethodError (Unsupported compression method 9)

### ISSUE THREAD

**Issue by aakanksha0402** [rubyzip/rubyzip#337]
Hello, 

I'm working with Rails 5.0.1 and rubyzip 1.2.1. I'm working on a project where the user will be uploading large zip files and i'm using paperclip for uploading. After the files are uploaded to the server, they are being unzipped and saved. 

Note: The error occurred for file created in windows using the default "Right click -> Send -> Compressed Folder". Also, the uploaded file is very large.

Following is my code for unzipping the files:

   ```
 path = "path is generated dynamically"
    zip_path = "path of the zip"

    FileUtils.mkdir_p(path)

    Zip::File.open(zip_path) do |zip_file|
      zip_file.each do |f|
        fpath = File.join(destination, f.name.gsub(" ","_")) #Replacing the spaces with hyphens
        zip_file.extract(f, fpath) unless File.exist?(fpath)
      end
    end
```

So far i know this is related to the ```Deflate64``` algorithm used by windows but that's it. 

I have referred the following links:

1. https://github.com/resin-io/etcher/issues/1499
2. https://github.com/thejoshwolfe/yauzl/issues/58
3. https://github.com/rubyzip/rubyzip/issues/35
4. https://stackoverflow.com/questions/19441879/truezip-returning-unsupported-compression-method-error-when-extracting-large-fil
5. https://github.com/rubyzip/rubyzip/issues/249

though, i'm yet unsure of the solution here. Is there a workaround to unzip this file?

Please guide me as to what can be done here. Thanks.

**Comment by pujas13** [comment]
Did you get any answer for this?

**Comment by hainesr** [comment]
Sorry to come back to this after so long - maybe this answer will still be of some use.

The issue with Deflate64 is that it is a proprietary/closed format owned by PKWare and, as far as I know, there is no ruby implementation. If there is one that you know of please let me know, or you could implement it as an extension for rubyzip, like the bzip2 one: https://github.com/rubyzip/rubyzip-bzip2
