### ISSUE TITLE
zip_file#glob case insensitive

### ISSUE THREAD

**Issue by GeorgeZhukov** [rubyzip/rubyzip#338]
hi guys!
Could someone explain me how to find all files with case insensitive ext. So in my case, I want to get all images, I've tried this code:
```ruby
images = zip_file.glob('*.{jpg,jpeg,png}', File::FNM_CASEFOLD)
```
but gets empty array in result.
Now I used this workaround 
```ruby
images = zip_file.entries.keep_if { |file| /\.(png|jpg|jpeg)$/i =~ file.name }
```
but seems it's better to use #glob for this kind of job

Thanks!

**Comment by hainesr** [comment]
I think for your glob to work you need `File::FNM_EXTGLOB` as well. The underlying glob in rubyzip has this set by default, but setting your own flags will overwrite it, as is the case here.

Not sure what the best solution to this is really. Additive flags would make it impossible to turn off things like `File::FNM_PATHNAME` too. Maybe we shouldn't have *any* default flags for globbing?
