### ISSUE TITLE
File checksums changing

### ISSUE THREAD

**Issue by whunter** [rubyzip/rubyzip#339]
Hello,
I'm using rubyzip to extract datasets from an online repository that we maintain. I've tried using the example here:
https://github.com/rubyzip/rubyzip/blob/05916bf89181e1955118fd3ea059f18acac28cc8/samples/example_recursive.rb
It seems to work well for our use case except that the checksums on the files seem to be changing. I've tried setting `Zip.default_compression = Zlib::NO_COMPRESSION`. Are the files being modified in some other way? Is there a configuration option to prevent this?

Thank you.

**Comment by simonoff** [comment]
Because with such method zip file is changed.
