### ISSUE TITLE
Zip::ZipCompressionMethodError: Unsupported compression method 98

### ISSUE THREAD

**Issue by wlipa** [rubyzip/rubyzip#35]
Some versions of WinZip have a new compression method that's not compatible with rubyzip.  Unfortunately, some users create such files.

Also see:
http://support.microsoft.com/kb/938319

**Comment by hainesr** [comment]
As this is so old I'm going to close it. But if you do want to implement decompression of method 98 (PPMd version I, Rev 1) then you could do so in the style of the bzip2 one: https://github.com/rubyzip/rubyzip-bzip2
