### ISSUE TITLE
Could you release v1.2.2?

### ISSUE THREAD

**Issue by aeroastro** [rubyzip/rubyzip#357]
@simonoff 

It has been a long time (more than 1 year) since the last release of rubyzip 1.2.1 on Feb 8, 2017.
https://github.com/rubyzip/rubyzip/releases/tag/v1.2.1

Could you release a new version so that we can utilize the recently implemented bug fixes and features?

It would be very kind of you if you could tell me anything I can do on my end.

**Comment by tcdowney** [comment]
@simonoff any updates for this? We're currently pinned to a ref of this repo to pull down the gem, but it would be nice if there was an official release. 🙏 

Thanks!

**Comment by lisamcho** [comment]
+1

**Comment by gregmolnar** [comment]
This one can be closed.
