### ISSUE TITLE
NoMethodError: undefined method `&' for (59675/2):Rational when writing encrypted zipfiles

### ISSUE THREAD

**Issue by gee-forr** [rubyzip/rubyzip#373]
Hi there,

I'm constantly (and randomly) getting the above error whenever I try creating an encrypted zip file using the below snippet:

```ruby
zip = Zip::OutputStream.write_buffer(::StringIO.new(''), Zip::TraditionalEncrypter.new(pass)) do |zos|
  zos.put_next_entry file_name # <-- Exception raised on this line
  zos.write stream_string
end
```

I copied the snippet effectively verbatim from the README example.

If I retry the process, it normally works after a few times. For the life of me, I cannot find prior issues of this anywhere on the interwebs.

Can anyone shed some light on this issue?

I'm currently using RubyZip 1.2.1, on Ruby 2.3.4.

Thanks so much for this useful gem. I'm eager to help in anyway I can.

**Comment by gee-forr** [comment]
Small update...

It appears that its trying to do a bitwise AND on another integer. I've monkey patched the Rational class to support `#&(int)`, like so:

```ruby
class Rational
  def &(int)
    self.to_i & int
  end
end
```

But this can't be a good idea, can it? Initial testing seems to keep the zip intact and extractable with the supplied password, but I think I'm fixing the wrong problem.

**Comment by jspanjers** [comment]
Hi gee-forr,

I suspect that this is caused by rubyzip expecting to have 'x = 3 / 2' return an integer, while instead it is returning a Rational.

The reason might be the use of a "require 'mathn'" somewhere in your code or your gem's code.
The ruby-units gem is known to require mathn.
The use of mathn was deprecated in ruby 2.2 and removed in ruby 2.5.
See: https://github.com/ruby/mathn

Do you use mathn somewhere?

**Comment by gee-forr** [comment]
Hi @jspanjers - YES! We do use ruby-units.

This was for a very old (now sadly decommed) application that needed to work with bytes as a unit.

It's very strange that requiring mathn in one place, breaks code non-deterministically in a completely seperate place.

Computers... amirite?

**Comment by gee-forr** [comment]
I've added a [wiki article](https://github.com/rubyzip/rubyzip/wiki/Why-am-I-getting-a-NoMethodError:-undefined-method-%60&'-for-Rational%3F) here for future visitors from the google machine.

**Comment by hainesr** [comment]
Thank you so much for adding the wiki page @gee-forr!
