### ISSUE TITLE
Unable to find path of file stored in Active Storage

### ISSUE THREAD

**Issue by fahim-abdullah** [rubyzip/rubyzip#386]
I am using Rails 5.2 and ActiveStorage to let my users upload files in my app. I have all the uploaded files displayed in a table and I can choose to select which ones I want to download. After selecting, I will be able to download all of them in a zip file. To zip the files, I am using Rubyzip and I can't get to work properly.

I have tried two ways : 
1 - I tried [this way](https://stackoverflow.com/questions/44693925/how-to-download-multiple-files-from-s3-as-zip-format-in-rails-5-x-x-app) and faced this error 
No such file or directory @ rb_sysopen - /rails/active_storage/blobs/..../2234.py
This is my controller : 
```
def batch_download
  if params["record"].present?
    ids = params["record"].to_unsafe_h.map(&:first)

    if ids.present?
      folder_path = "#{Rails.root}/public/downloads/"
      zipfile_name = "#{Rails.root}/public/archive.zip"

      FileUtils.remove_dir(folder_path) if Dir.exist?(folder_path)
      FileUtils.remove_entry(zipfile_name) if File.exist?(zipfile_name)
      Dir.mkdir("#{Rails.root}/public/downloads")

      Record.where(id: ids).each do |attachment|
        open(folder_path + "#{attachment.file.filename}", 'wb') do |file|
          file << open("#{rails_blob_path(attachment.file)}").read
        end
      end

      input_filenames = Dir.entries(folder_path).select {|f| !File.directory? f}

      Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
        input_filenames.each do |attachment|
          zipfile.add(attachment,File.join(folder_path,attachment))
        end
      end

      send_file(File.join("#{Rails.root}/public/", 'archive.zip'), :type => 'application/zip', :filename => "#{Time.now.to_date}.zip")
    end
  else
    redirect_back fallback_location: root_path
  end
end
```

2 - Secondly I tried to follow the rubyzip documentation and the error was a bit different. 
No such file or directory @ rb_file_s_lstat - /rails/active_storage/blobs/..../2234.py
```
if ids.present?
      folder = []
      input_filenames = []
      Record.where(id: ids).each do |attachment| 
        input_filenames.push("#{attachment.file.filename}")
        pre_path = "/rails/active_storage/blobs/"
        path_find = "#{rails_blob_path(attachment.file)}"
        folder.push(pre_path + path_find.split('/')[4])
      end
      container = Hash[folder.zip(input_filenames)]

      zipfile_name = "/Users/fahimabdullah/Documents/archive.zip"

      Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
        # input_filenames.each do |filename|
        container.map do |path, filename|
        zipfile.add(filename, File.join(path, filename))
        end
        zipfile.get_output_stream("myFile") { |f| f.write "myFile contains just this" }
      end
```
Help with this will be much appreciated. Thank you.

**Comment by jdleesmiller** [comment]
I think this more a usage question than a bug report in the gem, so it would be better suited to StackOverflow. You can ask it there with using the rubyzip tag: https://stackoverflow.com/questions/tagged/rubyzip

**Comment by JensDebergh** [comment]
I just wanted to say that I'm experiencing the same issue.

When a tempfile is created through activestorage rails its there, but once you hand it to `zipfile.add` the tempfile isn't there anymore (even before tempfile.close) is called.

Is there some async stuff going on with the `zipfile.add` function?  Where it may lose its reference while processing.

**Comment by JensDebergh** [comment]
Hi @hainesr

Thanks for the clear explanation. That might explain why the `Tempfiles` are not available anymore.

The zipfile I'm creating (that has the problems) has ±150 entries. I run an invoicing solution with expense management aswel.

When exporting the expenses:

1. We download the expenses from a S3 bucket (tempfile)
2. We then call `zipfile.add(tempfile.path)`
3. At some point during the writing we get an error `No such file or directory @ rb_sysopen`

I was under the impression `zipfile.add` did the actual writing (i'm not too familiar with IO operations)

So my best bet is that the `Tempfile` already gets garbage collected by the time it attempts to write it to the zipfile. Essentially deleting the file in the process.

How would I go best about this problem?

2 solutions come to mind:

1) Store all the references of the tempfile so they don't get deleted before the zip is written (and cleanup after the write)
2) Create a zip and keep open / writing / closing

Greatly appreciate your explanation!

**Comment by hainesr** [comment]
Hi @JensDebergh,

If you can do it all in one place in a nested block then you should be able to avoid race conditions. Something like:
```ruby
Dir.mktmpdir do |tmpdir|
  zipfile_name = ::File.join(tmpdir, 'archive.zip')

  Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
    # Download files and add to `zipfile` here.
  end

  # Send `zipfile_name` to user here.
end # `tmpdir` will be deleted here.
```

If you need to keep the zipfiles around after you've created them then don't create them in `tmpdir`!

Would that sort of thing work for your situation?

**Comment by JensDebergh** [comment]
Hi!

That's already what I am doing:

```
    Zip::File.open(archive_path, Zip::File::CREATE) do |zipfile|
      expenses.find_each do |expense|
        # 1. Get file name
        file_name = expense.attachment_file_name

        # 2. Open file
        current_file = URI.open(expense.attachment_url)

        # 3. Check if file exists
        if current_file
          # 4. Write to zipfile
          zipfile.add("#{expense.invoiced_on.strftime('%Y%m%d')}_#{file_name}", current_file.path)
        end
      rescue OpenURI::HTTPError => e
        Sentry.capture_exception(e)
      ensure
        # 5. Close file
        current_file.close unless current_file.closed?
      end
    end
    ```
    
 This exact piece of code gives file not found errors sometimes. If the list is small like in local development environment you won't experience this.

**Comment by hainesr** [comment]
Don't you hit the `ensure` - which closes `current_file` - before the end of the `Zip::File.open` block? This would mean that we can't read from `current_file` when building the zipfile at the end of that block.

**Comment by hainesr** [comment]
Yes, so every time you get to the end of the inner block, whatever is pointed to by `current_file` is closed. So when rubyzip needs to read the data at the end of the `Zip::File.open` block everything is closed.

Given that you are copying data from URI streams, I think you may be better using the `Zip::OutputStream` API instead of the `Zip::File` API.

Try something like this:
```ruby
::Zip::OutputStream.open(archive_path) do |zipfile|
  expenses.find_each do |expense|
    # 1. Get file name
    file_name = expense.attachment_file_name

    # 2. Open file
    current_file = URI.open(expense.attachment_url)

    # 3. Check if file exists
    if current_file
      # 4. Write to zipfile
      zipfile.put_next_entry("#{expense.invoiced_on.strftime('%Y%m%d')}_#{file_name}")
      zipfile << current_file.read
    end
  rescue OpenURI::HTTPError => e
    Sentry.capture_exception(e)
  ensure
    # 5. Close file
    current_file.close unless current_file.closed?
  end
end
```

This will write the data into the archive directly so you can close things off immediately without there being issues.

**Comment by JensDebergh** [comment]
Thank you for the support! I managed to get it fixed AND learned something new in the process.

Didn't know it was possible to create temp directories that easily in ruby!

**Comment by hainesr** [comment]
Great! Glad we could get it fixed...
