### ISSUE TITLE
Error No such file or directory using Zip::File.open for very large number of files

### ISSUE THREAD

**Issue by rohitcoupa** [rubyzip/rubyzip#389]
Our code in production suddenly started throwing error when we started exporting over 140 files to zip.
**error** : `No such file or directory @ rb_sysopen - /mnt/tmp/<pdf-file-name>`

Here is the snippet of the code we use.
```
file = Tempfile.new("temp_report_#{Time.now.to_i}")
Zip::File.open(file.path, Zip::File::CREATE) do |archive|
        archive.truncate
        pdf_files.each do |pdf_file|
           att_tmp_path = Paperclip.io_adapters.for(pdf_file).path
           
           if File.exist? att_tmp_path
              archive.add_file(pdf_file.original_filename, att_tmp_path)
           end
        end
end
```

This code works alright when the number of `pdf_files` are less than 120, but starts throwing these sort of errors every time when the `pdf_files` contain anything over 140 objects.

I tried to see if using `archive.add` would help instead of `archive.add_file` since it was taking the file object.
`archive.add(pdf_file.original_filename, File.open(att_tmp_path))`
instead of
` archive.add_file(pdf_file.original_filename, att_tmp_path)`
the same issue persisted, it didn't help.

I put loggers to check if all the files's path exist when the block is executing the last PDF record in the `pdf_files`.
```
archive.to_a.each_with_index do |zippity, index|
    puts "file_exist: #{File.exist?(zippity.filepath)} index: #{index} file_path: #{zippity.filepath}"
end
```
All the files **did exist** for each of the `Zip::Entry.to_a` objects.
But as soon as the block reaches end, it throws the error `No such file or directory @ rb_sysopen - /mnt/tmp/<pdf-file-name>`

Somehow the files get cleared(deleted) in the `temp folder` before it could ZIP them.
I was able to reproduce the same issue consistently on my local machine as well.
`No such file or directory @ rb_sysopen - /var/folders/9f/cs6_2_rd73g1s22nvjg6_7xw0000gn/T/<pdf file name>`

I am not sure what is making the temp files to get cleared.
Any help will be much appreciated to point us in the right direction.

I am using gem version `1.2.2`

**Comment by rohitcoupa** [comment]
This issue was due to paperclip's pdf paths being cleared. Closing this one.

**Comment by Toucouleur66** [comment]
> This issue was due to paperclip's pdf paths being cleared. Closing this one.

Can you explain a bit more, cause I have the exact same issue and don't know how to solve it
