### ISSUE TITLE
Update minimum required ruby version to more closely match maintained rubies?

### ISSUE THREAD

**Issue by hainesr** [rubyzip/rubyzip#404]
In the gemspec we currently have: `required_ruby_version = '>= 1.9.2'`. The latest maintained ruby is 2.4.

Should we bump up the version of ruby in the gemspec? If not all the way to 2.4 (a bit harsh). maybe at least to 2.2 or (my preference) 2.3?

Requiring a more modern ruby would make things like testing and linting easier, and it would allow us to use nice (and more performant) features as well.

Thoughts (especially @jdleesmiller)?

**Comment by jdleesmiller** [comment]
Yes, I think if we are going to do a major version bump, we should take the opportunity to drop support for EOL rubies. I would be OK with dropping (official) 2.3 support now. It has been EOL for [nearly 6 months](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/).
