### ISSUE TITLE
Recent update to require ruby 2.4 broke production code

### ISSUE THREAD

**Issue by afanofosc** [rubyzip/rubyzip#409]
The windows chef cookbook does not specify a rubyzip version so it gets the latest one available.  Since this gem was just updated to 2.0 and requires a newer version of ruby than is used in production all of our chef runs are failing now with "rubyzip requires Ruby version >= 2.4".

Please rollback this change ASAP.

**Comment by jdleesmiller** [comment]
Sorry to hear that this caused a problem.

We dropped support for older rubies in a major version bump --- i.e. one that can include breaking changes according to [semver](https://semver.org/).

Clients that need to use a ruby < 2.4, which is [end out of support](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/), should lock their dependencies down to rubyzip 1.3.

It would be best to make a fix on the chef cookbook side.

**Comment by afanofosc** [comment]
We have modified the version of the windows community cookbook so that it specifies the older release of rubyzip. Sadly, there will be a lot of companies running production code with older versions of chef who can't easily upgrade to newer community cookbooks who will experience breaking changes due to dropping support for older versions of ruby. Perhaps it would be worth considering alternatives to dropping support all of a sudden - perhaps deprecate with warnings for a while?  Is this new version really better in any way than the version that was working fine with all versions of ruby or call the new gem something different?  Like rubyzip2?
