### ISSUE TITLE
rubyzip-bzip2 repository

### ISSUE THREAD

**Issue by jspanjers** [rubyzip/rubyzip#430]
Hi,

I created an extension gem to support the bzip2 compression method.
You can find it at https://github.com/jspanjers/rubyzip-bzip2.

I would like to transfer this repository to the rubyzip organisation at github.
Are you okay with this transfer?

To do the transfer, I would need create repository permission on the rubyzip organisation.
Could you provide this permission to me?

**Comment by jdleesmiller** [comment]
@jspanjers OK, I think you should have be able to transfer.

**Comment by jspanjers** [comment]
hi @jdleesmiller ,

I transferred the repository.

There are a few more things to do:

- [ ] Enable coveralls

- [ ] Enable code climate

- [ ] Make a release of the gem and upload it to rubygems

Could you take care of these things?

**Comment by jdleesmiller** [comment]
Yes, will review and aim to release soon. Thanks!

**Comment by jdleesmiller** [comment]
I've pushed to rubygems so you can test there. Still not really sure why coveralls is not working... but will look at that later.

**Comment by jdleesmiller** [comment]
... and it seems to have fixed itself. So, I think this is all set.
