### ISSUE TITLE
Set compression on a per-operation basis

### ISSUE THREAD

**Issue by rlugge** [rubyzip/rubyzip#433]
There may already be an API for this that I'm not seeing, but it would be nice to be able to set the compression on a per-operation basis.  Something along the lines of:

```  def write(compress: false)
    entries = Dir.entries(@inputDir); entries.delete("."); entries.delete("..")
    io = Zip::File.open(
      @outputFile, Zip::File::CREATE,
      { compression: Zlib::BEST_COMPRESSION } # New Part
    );

    writeEntries(entries, "", io)
    io.close();
  end```

Right at the moment, it only appears possible (based on the documentation) to set this setting globally, which is rather annoying.

**Comment by hainesr** [comment]
Yes. Looking at this, it seems that there is an API a bit deeper in to be able to do this per entry even, but it's not exposed higher up the stack.

Before I go any further looking at this, what is the behaviour you are looking for here? Above you are suggesting that it would be good to be able to control this per zip file (I agree), but would it be useful to be able to control the per entry in a zip file too?

**Comment by rlugge** [comment]
I honestly can't see any utility in doing it per file.  Setting it per operation is enough.
