### ISSUE TITLE
rubyzip release gem contains test zip file with password

### ISSUE THREAD

**Issue by constantind** [rubyzip/rubyzip#442]
With rubyzip-1.3.0.gem
mcafee virus scan reports: "rubyzip-1.3.0.gem/data.tar.gz/data.tar/zipWithEncryption.zip/file1.txt ... is password-protected" and some policies may block this.
Ideally the release gem should not contain test and/or sample data.

**Comment by jdleesmiller** [comment]
Thanks for getting in touch. The test files were removed in the 2.0 release:
https://github.com/rubyzip/rubyzip/releases/tag/v2.0.0

See also https://github.com/rubyzip/rubyzip/issues/384
