### ISSUE TITLE
Encoding::UndefinedConversionError "from ASCII-8BIT to UTF-8"

### ISSUE THREAD

**Issue by eliten00b** [rubyzip/rubyzip#446]
With the change to enforce `binmode` I get the `Encoding::UndefinedConversionError` when using a snippet like this.

```ruby
zip = Zip::File.open('ä_uncommon_filename.zip')
buffer = Zip::OutputStream.write_buffer do |out|
  zip.entries.each do |entry|
    entry_name = entry.name.force_encoding('UTF-8')
    unless entry_name.valid_encoding?
      entry_name = entry_name.encode('UTF-8', invalid: :replace, undef: :replace, replace: '')
    end
    entry_name = ActiveSupport::Inflector.transliterate(entry_name).gsub(%r{\A/}, '')
    next if entry_name.blank?
    out.put_next_entry entry_name
    out.write entry.get_input_stream.read if entry.get_input_stream.is_a? Zip::InputStream
  end
end
File.open(processed_zip, 'w') { |f| f.write(buffer.string) }
```

The error is raised add the end in the `write` (`f.write(buffer.string)`). It did only happen if the `original` zip filename has a non-acsii character.

**Comment by eliten00b** [comment]
Also files with non-ascii characters inside the zip make problems.

**Comment by hainesr** [comment]
Do you have a snippet that replicates this without the `ActiveSupport::Inflector`?

**Comment by eliten00b** [comment]
Found the solution. The new file need to be open in binmode too.
`File.open(processed_zip, 'wb') { |f| f.write(buffer.string) }`

**Comment by hainesr** [comment]
OK thanks for letting us know.

Out of interest, which version of Ruby are you using? I couldn't replicate the error you had (although I wasn't running the `ActiveSupport` line) with plain `'w'`.

**Comment by eliten00b** [comment]
ruby: 2.6.5p114
rails: 6.0.3.1
