### ISSUE TITLE
Implement #size for Zip::InputStream for use with S3

### ISSUE THREAD

**Issue by jondavidjohn** [rubyzip/rubyzip#451]
My use case is to unzip a very large file that is in S3.

The primary constraint I have (due to the nature of the file sizes), is to not store the entire file in memory.

My thought was I could stream the unzip process both out and into my S3 bucket.

Example:

```ruby
      object = s3.get_object(bucket: bucket, key: file)
      Zip::InputStream.open(object.body) do |io|
        while (entry = io.get_next_entry)
          s3.put_object({ bucket: bucket,
                          key: "#{entry.name}",
                          body: entry.get_input_stream })
        end
      end
```

Being that `object.body` is an `StringIO` like object, this works up until I pass `entry.get_input_stream` because `Zip::InputStream` does not implement `#size`

So I end up getting

```
undefined method `size' for #<Zip::InputStream:0x0000559716b91060>
```

Looks like maybe this might fit in `Zip::IOExtras::AbstractInputStream`?

**Comment by jondavidjohn** [comment]
I was actually able to get it to work with the following patch.

```ruby
module Zip
  class InputStream
    def size
      @current_entry.size
    end
  end
end
```

Would you be interested in a PR for this?

**Comment by hainesr** [comment]
I wonder if this is safe in the case where the entry size has been artificially lowered (e.g. a Zip bomb)? Presumably it would be the responsibility of the receiver - S3 in this case - to limit the size of the uploaded data?

**Comment by jondavidjohn** [comment]
Honestly not familiar enough with the concept of a Zip bomb to know what the answer would be. ¯\_(ツ)_/¯

**Comment by jondavidjohn** [comment]
@hainesr Thanks 🙌

**Comment by aliismayilov** [comment]
Are there any plans for another 2.x release, so that this change could be included in a stable release?

**Comment by hainesr** [comment]
This won't go in 2.x, but 3.x is getting closer, I promise...
