### ISSUE TITLE
Documentation on how to read encrypted archives needed.

### ISSUE THREAD

**Issue by weshatheleopard** [rubyzip/rubyzip#453]
From what I reckon, the gem already has this capability. But figuring out how to **actually** do that is anything but easy.

**Comment by rubyFeedback** [comment]
Perhaps a short example on the main README.md may be useful; or a test-file in the gem to show this (brief example), or both.

**Comment by sandstrom** [comment]
@hainesr I'd close this one. Encrypted Zip files are rarely used. So I'm not convinced it's worth the added work and maintenance cost.

If anyone wants to open a PR with updates to the readme, then consider it. But to keep the number of issues down, I'd just close this (or move to discussions tab; after enabling it).

**Comment by hainesr** [comment]
Besides which, the info is in the README here: https://github.com/rubyzip/rubyzip/blob/master/README.md#password-protection-experimental
