### ISSUE TITLE
read remainder of entry through input stream fails if a partial read has already been performed.

### ISSUE THREAD

**Issue by paulmer** [rubyzip/rubyzip#461]
/lib/zip/ioextras/abstract_input_stream.rb line 22 does not check number_of_bytes for nil before using it.  If the output buffer is not empty due to a partial read on the stream, and a read with no parameters is performed then NoMethodError is raised instead of returning the remainder of the stream.  Can be reproduced via this pseudocode:

z = Zip::File.open('my-zip-file.zip')
e = z.entries.first # Assume first entry is a file
s = e.get_input_stream  # get an input stream to read the file entry
l = s.readline # read the first line of the entry
r = s.read # read remainder of entry
#<NoMethodError: undefined method `<=' for nil:NilClass>

**Comment by hainesr** [comment]
Thanks for spotting this. I think the linked PR will fix this.
