### ISSUE TITLE
zipfile.add records current datetime instead of original file's in Windows10 64bit

### ISSUE THREAD

**Issue by pelton1231** [rubyzip/rubyzip#465]
#Ruby version 2.7.2. patch 137  64bit
#Rubyzip 2.3.0
#Windows 10.0.19041   64bit

AAAA)
require 'zip'
zf = Zip::File.open('yoshi.zip', Zip::File::CREATE)
e = zf.add('myfile.txt','myfile.txt'  #e.time is CURRENT TIME, not the original file's, under W10
zf.close

The zip file is created, the entry added correctly, but the file date on the zip file is the CURRENT, not the original's.
Same code in UBUNTU 12.10 -works correctly. The original file date is in the zip.

I thought it was a problem of the NTFS file date which is different from FAT's. 
However, on a memory stick FAT or EXTFAT, the problem is identical.

BBBB)
So I tried a circumvention to manipulate the entry date. 

zf = Zip::File.open('yoshi.zip', Zip::File::CREATE)
e = zf.add('myfile.txt','myfile.txt'  #e.time is CURRENT TIME, not the original file's, in W10
e.time = File.mtime('myfile.txt') # that seems to work: puts e.time yields the correct value.
zf.close #that FAILS , however. Full stack below. In W10 AND Ubuntu 12.10

That one fails with "NoMethodError: undefined method 'to_binary_dos_time', in BOTH Windows and Linux. 
Am I missing something ? e.time= is a method that is accessible from outside. It crates the .extra structure
The method is not actually missing from the GEM, but fails to be referenced or executed correctly: dos_time.rb

C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/entry.rb:290:in `pack_local_entry': undefined method `to_binary_dos_time' for 1997-11-28 21:59:24 +0100:Time (NoMethodError)
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/entry.rb:304:in `write_local_entry'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/output_stream.rb:148:in `init_next_entry'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/output_stream.rb:105:in `put_next_entry'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/entry.rb:582:in `write_to_zip_output_stream'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:352:in `block (3 levels) in commit'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/entry_set.rb:38:in `block in each'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/entry_set.rb:37:in `each'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/entry_set.rb:37:in `each'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:351:in `block (2 levels) in commit'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/output_stream.rb:54:in `open'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:350:in `block in commit'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:454:in `block in on_success_replace'
	from C:/Ruby27-x64/lib/ruby/2.7.0/tmpdir.rb:129:in `create'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:452:in `on_success_replace'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:349:in `commit'
	from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:373:in `close'
	from bugreport.rb:7:in `<main>'
>Exit code: 1

**Comment by hainesr** [comment]
Currently we simply don't grab that information from a file under windows. I don't know why! Does `File::stat` not work under Windows?

For the second issue (`e.time`) there is a bug there - we should convert supplied Time objects into the internal DOSTime object.

**Comment by hainesr** [comment]
I think I have fixed both of these issues, but our tests are currently broken on Windows (at least in CI due to needing an external `zip` program).

@pelton1231, if you are able it would be great if you could test the current HEAD on Windows as above and let me know how you get on. Thanks.

**Comment by hainesr** [comment]
Pretty sure this is fixed now and the Windows tests are working in CI to confirm.
