### ISSUE TITLE
"Invalid code lengths set" when extracting an xlsx from a buffer

### ISSUE THREAD

**Issue by kalsan** [rubyzip/rubyzip#466]
Hi there! This is a bug report that can be reproduced as follows:

- a ZIP file contains several files in a subdirectory, one of them being an xlsx file
- the ZIP is downloaded via Ruby Net::SFTP and stored in a buffer (using `buff = sftp.file.open(path, 'r', &:read)`)
- the `buff` is then given to `Zip::File.open_buffer(buff)`
- attempt to extract or `get_input_stream.read` on the xlsx file from the ZIP results in:

```
Zip::DecompressionError: zlib error while inflating
from /app/vendor/bundle/gems/rubyzip-2.3.0/lib/zip/inflater.rb:41:in `rescue in produce_input'
Caused by Zlib::DataError: invalid stored block lengths
from /app/vendor/bundle/gems/rubyzip-2.3.0/lib/zip/inflater.rb:33:in `inflate'
```

Reproduced in rubyzip 2.0.0 and 2.3.0. Note that the error does not occur if `open` instead of `open_buff` is used.

Cheers!

**Comment by bbuchalter** [comment]
👋 This is a pretty complex issue to reproduce. Have you tried adding a failing test to rubyzip that demonstrates the behavior you are observing?

**Comment by kalsan** [comment]
Hi and thanks for coming back! I've desperately tried to come up with a more simple example. In particular, I have attempted to re-create the problem with first using `Pathname.read` and then `open_buffer` on the same file and it does not not-work... it's frustrating.
Given the long struggle for reproducing the issue in a lab setup, I was hoping that you might have an intuition or experience with a similar issue. If that is not the case, we can close the case since we'll probably never be able to reproduce it in useful time.

**Comment by hainesr** [comment]
I'm sorry I can't reproduce this. I wonder if the file is getting mangled or truncated by the `sftp` step? Can you compare the buffer read in from `Net::SFTP` to that read by `File`?

**Comment by kalsan** [comment]
@hainesr unfortunately the application reproducing the error was built for a specific task and has been terminated after the completion, so I cannot reproduce it anymore either. I'll close the issue and re-open if the error occurs again.

**Comment by hainesr** [comment]
Many thanks for letting us know @kalsan.

**Comment by 308820773** [comment]
```ruby
    string_buffer = Zip::OutputStream.write_buffer(::StringIO.new('test'), Zip::TraditionalEncrypter.new('1')) do |out|
      out.put_next_entry('1.test')
      out.write string_io.read
    end.string

    zip_file = Tempfile.new(["1", ".zip"])
    zip_file.binmode
    zip_file.puts string_buffer


    Zip::InputStream.open(::StringIO.new(zip_file.open.read), 0, Zip::TraditionalDecrypter.new("1")) do |input|
      entry = input.get_next_entry
      name  = entry.name.force_encoding('utf-8')
      File.open(name, 'w+') { |f| f.puts entry.get_input_stream.read }
    end

```

I get a error, 
Zip::DecompressionError:
       zlib error while inflating
