### ISSUE TITLE
travis-ci.org migration to travis-ci.com

### ISSUE THREAD

**Issue by bbuchalter** [rubyzip/rubyzip#469]
I noticed this repository is using travis-ci.org. A banner on travis-ci.org reads "Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information."

https://docs.travis-ci.com/user/migrate/open-source-repository-migration#do-i-need-to-make-any-other-changes suggests that changes will need to be made if this repository is using the "Protected Branches" GitHub feature to ensure a passing build before merging.

Since that's a common practice, I assume this setting will need to be modified.

**Comment by ShockwaveNN** [comment]
I think it's better idea to migrate to GitHub Actions instead, since travis new managers killed the project for opensource

**Comment by hainesr** [comment]
I agree with @ShockwaveNN. Once travis-ci.org shuts down individuals who want to submit to the rubyzip codebase will all need to individually get "opensource tokens" or pay for the service. It's already prevented me from submitting a couple of patches here because I moved things to travis.com unaware of the full consequences of doing so.

**Comment by ShockwaveNN** [comment]
@hainesr I've moved plenty of my CI (they pretty simple, without support any non-MRI rubyies) from Travis to GitHub Actions and Actions are great, they're faster and more integrated in GitHub

Current .travis.yml file looks pretty simple, except for webhook part in end https://github.com/rubyzip/rubyzip/blob/master/.travis.yml#L43

But I think coveralls service may support Actions as well as travis

**Comment by hainesr** [comment]
I've added a couple of actions for testing and linting, and I've created a new issue (#480) to remind me to connect coveralls in.

I've left the Travis config in place for now.
