### ISSUE TITLE
Zip files from remote location

### ISSUE THREAD

**Issue by OGsoundFX** [rubyzip/rubyzip#477]
I hope this is the right place to ask this question:

I implemented this gem into my rails app. It works perfectly when I want to zip local files, but I can't seem to find a way to zip remote files. Is it even possible?
Thank you in advance for your replies.
Olivier

**Comment by hainesr** [comment]
What do you mean by remote files? Are you talking about files in e.g. S3 as with #451?

**Comment by OGsoundFX** [comment]
I mean files that are hosted on a different server than the application itself.
For example, I host my application on Heroku but the download files (that I wish to zip when a user wants to download them) are hosted on a completely different location.

**Comment by hainesr** [comment]
I think it's not possible to do what you want - at least not "in place". You'd have to stream/copy your files to somewhere you can run rubyzip and then back again, or to the user. This would be the case with command-line zip as well - you need the data where you can execute something to be able to operate on it.

**Comment by OGsoundFX** [comment]
Thanks for your reply, it is very helpful!
