### ISSUE TITLE
Question: Read the zip as a stream, and upload to Active::Storage

### ISSUE THREAD

**Issue by stoivo** [rubyzip/rubyzip#478]
I have a zip with files I want to upload to active storage. Some of the files can be several gigabytes so it's important to me that I don't read the whole string into memory. ActiveStorage ueses s3 which needs to know the length ahead. The `Zip::InputStream` does not expose a size method. I deep my feet into the source and found that `Zip::InputStream` as a @current_entry which was a size method. 

I did a little monkey patching 🙊 
```ruby
class Zip::InputStream
  def size
    return nil unless @current_entry

    @current_entry.size
  end
end
```

Now my usage has become 
```ruby
Zip::File.open(ENV["BACKUPZIP"]) do |zip_file|
  zip_file.each do |entry|
    blob = ActiveStorage::Blob.find_by(key: entry.name.split("/").last)
    next unless blob

     entry.get_input_stream do |io|
       blob.upload io
     end
  end
end
```

My question is if this is a patch you want to have into rubyzip?
Do you want me to make a PR?

**Comment by stoivo** [comment]
Closing because it is a duplicate of https://github.com/rubyzip/rubyzip/issues/451

**Comment by hainesr** [comment]
Thanks. I have commented on the other issue.
