### ISSUE TITLE
Attaching extended attribute (xattr) to file in zip

### ISSUE THREAD

**Issue by fjaeger** [rubyzip/rubyzip#479]
Is it possible to add an extended attribute (xattr) to a file in an existing zip archive with rubyzip?

**Comment by hainesr** [comment]
Do you mean add an extra field in the zip archive sense? E.g. section 4.5 here: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

**Comment by fjaeger** [comment]
No, I rather meant an extended attribute on the file system layer: https://en.wikipedia.org/wiki/Extended_file_attributes

**Comment by hainesr** [comment]
In that case, no sorry. From what I understand of the zip standard it isn't possible at all, let alone with rubyzip.
