### ISSUE TITLE
Refactor `assert_forwarded` in the tests?

### ISSUE THREAD

**Issue by hainesr** [rubyzip/rubyzip#482]
It's a horrible bit of code which obfuscates what it is doing; it relies on an API which is not recommended (`_id2ref`); it requires that `ObjectSpace` be enabled to run the JRuby tests; and, it currently breaks builds in TruffleRuby (albeit due to a bug in TruffleRuby oracle/truffleruby#2358).

Can we be rid of it?

**Comment by eregon** [comment]
I'll take a shot at this.

**Comment by eregon** [comment]
https://github.com/rubyzip/rubyzip/pull/483
