### ISSUE TITLE
Many tests failing under Windows.

### ISSUE THREAD

**Issue by hainesr** [rubyzip/rubyzip#485]
A lot of failures appear to be due to hardcoded paths into places like `/tmp` which should be easy to fix. Other tests appear to fail due to unexpected line endings - `\r\n` vs `\n` - which I think suggests that we're testing what comes out of a zip file (`\n`) with a text file that has been auto-converted to `\r\n` in the checkout process?

**Comment by hainesr** [comment]
I've started a branch with various attempts at fixes if anyone can help with this. Windows is not my strong point.

https://github.com/hainesr/rubyzip/tree/fix-windows-tests

**Comment by jspanjers** [comment]
Hi,

I am working on this, see https://github.com/jspanjers/rubyzip/tree/fix-windows-tests for progress.
