### ISSUE TITLE
Configure Coveralls to not report a failure on minor decreases of test coverage 

### ISSUE THREAD

**Issue by jspanjers** [rubyzip/rubyzip#491]
> It seems most of the Coveralls test fails with a decreased coverage of 0.0%.
However, when I look at the Coveralls details, I do not notice any decreased coverage.
Maybe this is a rounding error?

> Would it be possible to change the 'Coverage Decrease Threshold for failure' on https://coveralls.io/github/rubyzip/rubyzip/settings to something like, 0.1% ?

Yes, I hate Coveralls being so touchy by default, and I had no idea it could be adjusted! Also, while I like decent coverage, I'm not super bothered about it going up or down a bit when it's over 90% anyway. I'd be happy to have 90% as the threshold and then stop worrying about it. Unfortunately I don't have the required access to set this, as I'm not an owner of the rubyzip repo - maybe @jdleesmiller could set the threshold? Thanks!

_Originally posted by @hainesr in https://github.com/rubyzip/rubyzip/issues/488#issuecomment-855388592_

**Comment by jdleesmiller** [comment]
Agree that is annoying! I've set it to 0.5%.
