### ISSUE TITLE
Missing tests in .gem file 

### ISSUE THREAD

**Issue by mdb571** [rubyzip/rubyzip#500]
Can we include the tests as part of the gem itself ? I'm packaging this library for debian and I have to take a github tarball instead of the gem from rubygems.org . So it would be better if the test is available with the gem itself :)

**Comment by jdleesmiller** [comment]
Thanks for getting in touch. The tests contain some malicious zip files, which were triggering antivirus scanners, so we (I!) removed them --- background in https://github.com/rubyzip/rubyzip/issues/384 . So, I don't think we should add them back in.

**Comment by mdb571** [comment]
Okay thanks for the quick response. I'll use github tarball for preparing the package :)
