### ISSUE TITLE
docs: What should we do when complying with "Please check your usage of the following Rubyzip classes:"

### ISSUE THREAD

**Issue by doublethefish** [rubyzip/rubyzip#501]
Not being familiar with Ruby I don't know how to comply with this statement from the README, I don't even know where to start looking.
```
Version 3.0
The public API of some classes has been modernized to use named parameters for optional arguments. Please check your usage of the following Rubyzip classes:

File
Entry
InputStream
OutputStream
```

My preference would be to see some sort of hint, clarification, breadcrumb or starter-for-ten in the docs so we can follow the guideline?

**Comment by NEWeber** [comment]
+1, next steps would be helpful.

**Comment by hainesr** [comment]
Thanks, will try and sort this soon once I'm sure what all the changes will be.

**Comment by hainesr** [comment]
I am now populating a wiki page about the v3.0 API, which is also linked from the README.

https://github.com/rubyzip/rubyzip/wiki/Updating-to-version-3.x
