### ISSUE TITLE
Extracting large file is failing with the Error getting object: entry 'feed.xml' should be 511431006B, but is larger when inflated.

### ISSUE THREAD

**Issue by gobinath2389** [rubyzip/rubyzip#502]
Hi I am trying to extract the large file around 13 GB, but Zip extract was through the memory error. Any suggestions on how to fix this?

**Comment by hainesr** [comment]
This sounds like a mal-formed zip file that is reporting the wrong size for a file when inflated. By default rubyzip will raise an error in this situation in case it is a zip bomb.

If you **really** trust the source of the zipfile you can override this by setting `Zip.validate_entry_sizes = false` before trying to extract, but ⚠️ _we really don't recommend setting this in any general config_ ⚠️you have, for obvious reasons!

**Comment by hlarsen** [comment]
I'm working with some database dumps and I'm seeing the same `but is larger when inflated` error with the largest file; I have a few others that are a (lot) smaller that are not exhibiting this issue.

As you can see below, the zip created by `rubyzip` (v2.3.2) is showing an uncompressed file size of 3-4GB whereas the zip created by `zip` (linux) is showing the correct 16GB. I do note that in the return value `@size` has the correct uncompressed file size.

`unzip` (linux) decompresses both files correctly. Please let me know if there are any additional logs or debug steps I can provide.

The original file is about 16GB:
```
$ ls -l *.sql
-rw-r--r-- 1 hlarsen hlarsen 16594944137 Nov 19  2021 big-sql-file.sql
```

Zipping the file:
```
Zip::File.open("rubyzip-test.zip", create: true) do |zip_file|
  zip_file.add("big-sql-file.sql", "big-sql-file.sql")
end

#<Zip::Entry:0x0000564348fe0d80
 @comment="",
 @compressed_size=888178815,
 @compression_method=8,
 @crc=239686343,
 @dirty=false,
 @external_file_attributes=2175008768,
 @extra={},
 @filepath="big-sql-file.sql",
 @follow_symlinks=false,
 @fstype=3,
 @ftype=:file,
 @gp_flags=0,
 @header_signature=33639248,
 @internal_file_attributes=1,
 @local_header_offset=0,
 @local_header_size=55,
 @name="big-sql-file.sql",
 @restore_ownership=false,
 @restore_permissions=false,
 @restore_times=false,
 @size=16594944137,
 @time=2021-11-19 15:31:44 -0800,
 @unix_gid=1000,
 @unix_perms=420,
 @unix_uid=1000,
 @version=52,
 @version_needed_to_extract=20,
 @zipfile="rubyzip-test.zip">
```

Running `unzip -l` on the rubyzipped file:
```
# unzip -l rubyzip-test..zip
Archive:  rubyzip-test.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
3710042249  2021-11-19 15:31   big-mysql-file.sql
---------                     -------
3710042249                     1 file
```

Running `unzip -l` on a file zipped by `zip` v3.0 (linux):
```
# unzip -l a.zip
Archive:  a.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
16594944137  2021-11-19 15:31   big-mysql-file.sql
---------                     -------
16594944137                     1 file
```

**Comment by hainesr** [comment]
A-ha, I think I see what is happening now. Thank you for the detailed information, @hlarsen.

Standard Zip files can only store files sizes (both compressed size and uncompressed size) in 8 bytes and 16594944137 needs 9. So all looks OK in the `Entry` that you've given above, but when that gets written to disk, the uncompressed size gets truncated to 8 bytes. Then when reading it back in it sees the uncompressed file as a lot smaller than it should be (3710042249), and complains.

Just as a sanity check, the numbers all check out:
```ruby
[16_594_944_137].pack('V').unpack1('V')
 => 3710042249
```

Please can you try the above test again, but set `Zip.write_zip64_support = true` first?

**Comment by hlarsen** [comment]
@hainesr Yep, setting `Zip.write_zip64_support = true` fixes it - thanks!

**Comment by hainesr** [comment]
Great! Thanks again for your detailed report.
