### ISSUE TITLE
Consider enabling write_zip64_support by default?

### ISSUE THREAD

**Issue by owst** [rubyzip/rubyzip#521]
I accidentally created an invalid zip file by adding a single file with > 4GB of uncompressed data but without setting `Zip.write_zip64_support = true`. For example, `7z x` errors when attempting to extract the generated file.

In my case I quickly found the problem and recreated the zip file having enabled `write_zip64_support`, but I can imagine in some scenarios it may be a pain to (much?) later find that the generated file has been silently corrupted.

Is there a good reason _not_ to enable `write_zip64_support` by default? Or perhaps explicitly raise an error if `rubyzip` detects that it has written >4GB of data?

A simple reproduction:
```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rubyzip', "= 2.3.2"
end

require "zip"

ONE_MB_OF_A = "a" * 1024 * 1024

def write_zip(file_name, zip64_support:)
  Zip.write_zip64_support = zip64_support

  Zip::File.open(file_name, Zip::File::CREATE) do |zipfile|
    zipfile.get_output_stream("data.txt") do |data|
      (1024 * 4).times do |i|
        data << ONE_MB_OF_A
      end

      10.times do |i|
        data << "b"
      end
    end
  end
end

write_zip("example.zip", zip64_support: false)
write_zip("example64.zip", zip64_support: true)
```
writes out 4GB + 10 bytes of data, running `7z t example.zip` fails but `7z t example64.zip` passes

**Comment by hainesr** [comment]
Thanks for this. I would like to turn Zip64 on by default, and do intend to. There's a PR (#517) that does this, but I'm taking some time to make sure we do this in a way that doesn't break other things - see this comment to that PR: https://github.com/rubyzip/rubyzip/pull/517#issuecomment-1030266449.

I'll leave this issue open and close it once I get this sorted. I intend Zip64 to be on by default - or, even better, applied only when it needs to be by default - in version 3.

**Comment by owst** [comment]
Thanks @hainesr - apologies for missing the already-open PR. Your suggestion of enabling Zip64 when required sounds good

**Comment by owst** [comment]
Hi @hainesr - just checking in on the progress of this? I've just been bitten again by this issue (my fault for not remembering to enable `write_zip64_support`) - it would be great if rubyzip would help me by enabling that option when necessary (or by default!)

**Comment by hainesr** [comment]
I have just created a new PR (#541) which will fix this issue. Please test if you can.
