### ISSUE TITLE
Entry#unpack_local_entry can't get  compressed_size

### ISSUE THREAD

**Issue by blackerhand** [rubyzip/rubyzip#525]
First, I get a zip file use mac osx, (select 2 file, right-click,  select compress). 

Second, I use Zip::File open it, I can get right.   Zip::InputStream is error(only get one entry). 

```ruby 
Zip::File.open('2.zip') do |zip_file|
  zip_file.each do |entry|
    puts "Extracting #{entry.name}" 
    entry.compressed_size #  > 0 
  end
end

input = Zip::InputStream.open(::StringIO.new(io), 0, decrypter)
while entry = input.get_next_entry

entry.compressed_size  # = 0  
# I can't get the second file, because offset not right
```

Because the zip file has a password,  I must use Zip::InputStream

ruby 2.6.6p146
rubyzip (2.3.2)

**Comment by blackerhand** [comment]
```
def unpack_local_entry(buf)
      @header_signature,
        @version,
        @fstype,
        @gp_flags,
        @compression_method,
        @last_mod_time,
        @last_mod_date,
        @crc,
        @compressed_size,
        @size,
        @name_length,
        @extra_length = buf.unpack('VCCvvvvVVVvv')

# compressed_size is 0
```

**Comment by blackerhand** [comment]
Checkout rubyzip 3.0.0, I get error: 

Zip::GPFBit3Error:
       It is not possible to get complete info from the local header to extract this entry (GP flags bit 3 is set). Please use `Zip::File` instead of `Zip::InputStream`.

But Zip::File not supprot decrypter, It can be a constant cycle.  

I close this issue, please check it. Thanks.

**Comment by blackerhand** [comment]
@hainesr

**Comment by hainesr** [comment]
This is partly an issue with zip archives created by Archive on OSX - there's a bit of an explanation here: https://github.com/rubyzip/rubyzip/issues/510#issuecomment-975603520

We do need to enable reading/writing encrypted zips via `Zip::File`, which is noted as an issue here: #519
