### ISSUE TITLE
Undefined method `reopen' for "streamed":String

### ISSUE THREAD

**Issue by tristrambrelstaff** [rubyzip/rubyzip#526]
Am getting this error:
```
undefined method `reopen' for "streamed":String
```
at:
```
rubyzip (1.3.0) lib/zip/output_stream.rb:32:in `initialize'
```

The rubyzip code that fails is:
```
      @output_stream = if stream                                                                                                                      
                         iostream = @file_name.dup                                                                                                    
                         iostream.reopen(@file_name)       <<< line 32                                                                                           
                         iostream.rewind                                                                                                              
                         iostream                                                                                                                     
                       else                                                                                                                           
                         ::File.new(@file_name, 'wb')                                                                                                 
                       end                                                                                                                            
```

The line setting iostream to the string @file_name.dup looks wrong to me as it will always cause the reopen to fail.

In 0.9.9 the corresponding code is:
```
      if stream                                                                                                                                       
        @outputStream = StringIO.new                                                                                                                  
      else                                                                                                                                            
        @outputStream = ::File.new(@fileName, "wb")                                                                                                   
      end                                                                                                                                             
```
If I replace the 4 iostream lines in 1.3.0 with StringIO.new then my code works as expected without crashing.

But I do not understand why the iostream lines were added and what they are intended to do so I am reluctant to suggest this is a suitable fix.

**Comment by hainesr** [comment]
Please can you give me more context? What are you passing in to this? And which platform and ruby version are you using?

The code has changed a bit since version 1.3.0, which is considered unsafe in other areas and shouldn't be used. I suspect version 2.3.2 is the same here, but could you try HEAD?

**Comment by Antimeta88** [comment]
Me estás escuchando Okay
Hello, good afternoon, my name is Juan Carlos. I am a guy from Mexico who
has invited me to participate in Google Developer.I apologize for how this
email came into your hands what happens is that in order to get enough
useful information for delvac bullying from the app I have to track all
over the cyber world system that I am using Gi.IOS, I AM MORE OR LESS
ACCLIMATING TO USING IT I THINK THAT ITS STRUCTURE IN SOME EXTERNAL WAY TO
SUPPORT IT IS CALLED RUBY WHICH IS MADE BY A GENIUS FROM FRANCE HE ALSO
USED PYTHON WHICH IS THE SAME BUT MORE POWERFUL BUT STILL NOT TAMMED THEY
HAVE A TENDENCY TO THROW ALMOST EVERYTHING AT YOU LIKE IT WAS ARES OR
LIMEWIRE IF YOU ADD TO THAT GI YOU GET A MAP

**Comment by Antimeta88** [comment]
Para grupo développer yo me inscribí en la parte de proyecto ya iniciado y
uno de ellos es el micrófono que depende la marca del celular o depende la
aplicación con la que lo estés usando es si funciona correctamente o si se
queda amarrado con situaciones en la escritura de las mismas tal y como nos
acaba de suceder a ti y a mí.
Y ahí empieza mi camino Juan Carlos Bautista Aguilar es el elegido para
solucionarlo obviamente voy a hacer dirigido y disciplinado le pido que me
tenga paciencia por favor ya casi gracias.
With love anti meta.

**Comment by tristrambrelstaff** [comment]
I think I now understand what happened:

The axlsx package was calling 
  Zip::ZipOutputStream.new("streamed", true)
where "streamed" is presumably meant to be the file_name and true indicates that input is an IOStream.
In the the console with Ruby 1.9.3 this crashes with 
  NoMethodError: undefined method `reopen' for "streamed":String

More recent versions of axlsx call
  Zip::ZipOutputStream.new(StringIO.new, true)
which makes more sense.
This does not crash in the console.

I have repeated the above with rubyzip 2.3.3 on ruby 3.0.0p with the same results.

Looks to me that this was a bug in axlsx.

**Comment by hainesr** [comment]
OK thanks for letting me know. Are you happy to close this issue now?

**Comment by tristrambrelstaff** [comment]
Yes
