### ISSUE TITLE
Remove zipWithEncryption.zip after test

### ISSUE THREAD

**Issue by danny5783** [rubyzip/rubyzip#536]
Some AV engines detect and delete password protected files unless the password can be supplied.  Today I had an entire 1GB tar.gz archive deleted because it contained a logstash rpm that uses this library.  Can the tests be modified to generate the encrypted zip and delete it once the test is complete.

**Comment by hainesr** [comment]
Hello. I am sorry to hear this.

Which version of the gem are you using? We no longer distribute the tests in the gem (on rubygems at least) for this exact reason.

**Comment by danny5783** [comment]
It was rubyzip-1.2.2.

**Comment by hainesr** [comment]
That is a pretty old version, which has some fairly nasty security holes and is no longer supported. If you can update to the latest on the v2.x line you'll get a more secure rubyzip and it won't have the tests in the gem.

**Comment by danny5783** [comment]
I'll mention that to the company that supplied it.  Our system is
air-gapped so I'm not too worried about the risks.

Thanks for your help.
