### ISSUE TITLE
65K file limit into zip file

### ISSUE THREAD

**Issue by mdwin01** [rubyzip/rubyzip#538]
There seems to be a limit of around 65,506 files ending up in my zip file out of a total of over 70K.  Is there a way to overcome this limitation?  I'm using [https://github.com/rubyzip/rubyzip/blob/9d891f7353e66052283562d3e252fe380bb4b199/samples/example_recursive.rb](url)

**Comment by hainesr** [comment]
Yes, the baseline Zip standard uses a 16bit number to store the number of files in an archive, so you're limited to `(1 << 16) - 1` (65,535) files by default.

If you set the Zip 64bit option you should be fine:
```ruby
Zip.write_zip64_support = true
```
