### ISSUE TITLE
Zip a CSV file with a password

### ISSUE THREAD

**Issue by macgill4444** [rubyzip/rubyzip#553]
Hey all, I'm trying to ZIP a CSV file with a password protection. I'm running into a lot issues and can't seem to get this working. Would you mind sharing a code snippet on how to do this?

**Comment by hainesr** [comment]
Hi, encryption isn't super-well supported in Rubyzip, but there is an example of how to do it in the Readme: https://github.com/rubyzip/rubyzip/blob/master/README.md#password-protection-experimental

If you've tried that, what problems are you seeing?

**Comment by sandstrom** [comment]
@hainesr I'd suggest enabling the 'discussions' tab on this repo, then move all questions there.

That way, you'd keep the list of actual issues shorter.

**Comment by sandstrom** [comment]
@hainesr I'd close this one. Encrypted Zip files are rarely used. So I'm not convinced it's worth the added work and maintenance cost.

99% of cases when you want to protect data a zipfile with encryption, you'd just wrap the encryption around the zip.

**Comment by hainesr** [comment]
Nearly a year and no response anyway, so I'll close.
