### ISSUE TITLE
Road to 3.0

### ISSUE THREAD

**Issue by sandstrom** [rubyzip/rubyzip#555]
It seems like 3.0 isn't released yet. Would be great with a new release!

I found this list of open issues pinned to that milestone:
https://github.com/rubyzip/rubyzip/milestone/2

May I suggest reducing that list to only breaking changes, and move all other items to a 3.1 milestone.

That way, maybe a 3.0 release can be created quicker.

### Supported Ruby

I'd consider raising the minimum Ruby version for the 3.0 release to be Ruby 3.0.

Since all other ruby versions are already end-of-life, and you're making a new major anyway, so no problem with an additional breaking change (min ruby).

That should also make it easier to migrate the whole gem over to using keyword arguments, instead of implicit option hashes (assuming this gem has used that pattern).

### Somewhat unrelated

Also, I'd suggest deleting the `TODO` file, it's role isn't entirely clear and it hasn't been modified in 10 years.

**Comment by kwerle** [comment]
And is there a path/timeline for the 3.0 release?

**Comment by hainesr** [comment]
Hi @sandstrom,

Thanks for this. I have indeed now deleted the `TODO` file, set Ruby 3.0 as the minimum, and pushed many of the issues back to a future milestone.

I now just need to fully document the changes, and I'm trying to prepare a 2.4 release that will help people move from 2.x to 3.x.

@kwerle I'm afraid I can't give a solid timeframe, but I'm focussing on it now (insomuch as time allows).
