### ISSUE TITLE
Invalid output from Rubyzip with Tempifile

### ISSUE THREAD

**Issue by ED-Y-S** [rubyzip/rubyzip#557]
```
static_zip = Tempfile.new('a.zip')
Zip::File.open(static_zip, Zip::File::CREATE) do |z|

    files.all do |file|
	    
	    temp_file = Tempfile.new(filename)
	    file.download(temp_file.path)
    
	    z.add(filename, temp_file.path)
    
    end 
 end

```

I've skipped something in between but all the essential parts are in there. After using download() to get the file from Google Cloud, the file was never added into the TempFile that is my zip. 

Even when the program spews out a zip file, it can't be opened by any unzip apps (eg., 7zip states that it's not an archive) and it has weird numbers/characters after .zip extension when I check the process on the terminal

What am I missing here?

**Comment by hainesr** [comment]
Firstly, using `Tempfile` will always give you the extra chars after the extension [1]. It assumes a multiuser system, and you may not be the only person making temporary files with that name.

To debug the other issue, are you sure all the data has landed before you add it into the zip file? I don't see any code above for the download, so I don't know how you're doing it. If you try adding files that you know are present on disk already, what happens?

[1] https://ruby-doc.org/2.7.8/stdlibs/tempfile/Tempfile.html

**Comment by ED-Y-S** [comment]
> Firstly, using `Tempfile` will always give you the extra chars after the extension [1]. It assumes a multiuser system, and you may not be the only person making temporary files with that name.
> 
> To debug the other issue, are you sure all the data has landed before you add it into the zip file? I don't see any code above for the download, so I don't know how you're doing it. If you try adding files that you know are present on disk already, what happens?
> 
> [1] https://ruby-doc.org/2.7.8/stdlibs/tempfile/Tempfile.html

Hi, thanks for your reply! I think that the downloading process is working properly on our program with the .download() method. If you don’t mind me asking, would I need to remove the extra char after the extension somehow or is it unnecessary to do so?

**Comment by hainesr** [comment]
I'd be surprised if a zip is being rejected purely based on file name/extention, but just in case you can force the `.zip` extension when using Tempfile by using the "Array" form of the new method: https://ruby-doc.org/2.7.8/stdlibs/tempfile/Tempfile.html#method-c-new

This will still give you all the extra characters, but they will be before the extension. If you really want to use `Tempfile`, and you really don't want the extra characters, then you'll need to rename your file after you close it.

**Comment by ED-Y-S** [comment]
> I'd be surprised if a zip is being rejected purely based on file name/extention, but just in case you can force the `.zip` extension when using Tempfile by using the "Array" form of the new method: https://ruby-doc.org/2.7.8/stdlibs/tempfile/Tempfile.html#method-c-new
> 
> This will still give you all the extra characters, but they will be before the extension. If you really want to use `Tempfile`, and you really don't want the extra characters, then you'll need to rename your file after you close it.

I will do exactly that! Thank you!
