### ISSUE TITLE
Compatibility Inquiry: rubyzip 3.0.0. alpha with Ruby 3.3.0

### ISSUE THREAD

**Issue by sydverisk** [rubyzip/rubyzip#567]
Hi,

I'm seeking confirmation regarding the compatibility of the rubyzip 3.0.0. alpha  with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on RubyGems and table mentioned on https://github.com/rubyzip/rubyzip?tab=readme-ov-file, https://rubygems.org/gems/rubyzip, it only specifies a minimum required Ruby version of 2.7.0. Unfortunately, I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by hainesr** [comment]
Hi @sydverisk, it should work. It's tested in CI, which you can track on the [Actions tab](https://github.com/rubyzip/rubyzip/actions). Given it's still alpha it could fluctuate a bit, but I'm hoping it's pretty stable now.

I've just updated the README with new [compatibility information](https://github.com/rubyzip/rubyzip/blob/master/README.md#compatibility), which will hopefully tell you what you need to know.

**Comment by sydverisk** [comment]
Hi @hainesr 
Thank you so much the update!
I appreciate it and looking forward to more amazing things!
