### ISSUE TITLE
Zlib::GzipWriter object must be closed explicitly

### ISSUE THREAD

**Issue by coreyward** [rubyzip/rubyzip#73]
I'm using the `Zip::ZipFile.open` method to create a zip file. My log ends up showing the following…

```
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
```

I'm not really sure what's going on, particularly because I was under the impression that using the block variant handled closing everything up.

**Comment by hainesr** [comment]
Zlib streams are closed explicitly now. Also, we don't use `GzipWriter` in rubyzip - so this might have come from elsewhere? (I'm aware this is an old issue - just going through and clearing up.)

**Comment by taf2** [comment]
curious we just saw this pop in our error logs today only 1 time...
```
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
```

**Comment by hainesr** [comment]
Can it have come from elsewhere? We don't use `GzipWriter` anywhere in rubyzip.
