### ISSUE TITLE
TypeError: can't dup NilClass

### ISSUE THREAD

**Issue by disbelief** [rubyzip/rubyzip#82]
I've been seeing the following stack trace when trying to create and write to a new zip file.

It happens sporadically, ie. not every single time, but enough to worry me. Wondering if someone could shed some like on it?

```
bundle/ruby/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_entry_set.rb:44:in `dup'
bundle/ruby/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_entry_set.rb:44:in `block in dup'
bundle/ruby/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_entry_set.rb:44:in `map'
bundle/ruby/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_entry_set.rb:44:in `dup'
bundle/ruby/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:75:in `initialize'
bundle/ruby/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:228:in `commit'
bundle/ruby/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:242:in `close'
bundle/ruby/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:92:in `open'
```

**Comment by philister** [comment]
Same here with 1.1.6
With more than ca. 200 files and a archive-size of ca 4.1G the following error occurs. Everytime. 
    TypeError: can't dup NilClass
        rubyzip-1.1.6/lib/zip/entry_set.rb:56:in `dup'
        rubyzip-1.1.6/lib/zip/entry_set.rb:56:in `block in dup'
        rubyzip-1.1.6/lib/zip/entry_set.rb:56:in `each'
        rubyzip-1.1.6/lib/zip/entry_set.rb:56:in `map'
        rubyzip-1.1.6/lib/zip/entry_set.rb:56:in `dup'
        rubyzip-1.1.6/lib/zip/file.rb:84:in `initialize'
        rubyzip-1.1.6/lib/zip/file.rb:312:in `commit'
        rubyzip-1.1.6/lib/zip/file.rb:325:in `close'
        rubyzip-1.1.6/lib/zip/file.rb:101:in `open'

    Zip::File.open(zipfile_name, Zip::File::CREATE) {
      |zipfile|
        images.collect { |image|
            [...]
            zipfile.add(targetname, image.srcpath)
        }
    }

What can I do? The file seems to be written (exists in the expected size with the filename), but not finished.

Thanks and regards, Phil

**Comment by philippbayer** [comment]
Have you initialized zip64 support in an initializer? Like here (ignore unicode and continue_on_exists)

https://github.com/gedankenstuecke/snpr/blob/master/config/initializers/zip.rb

**Comment by philister** [comment]
Thank you! That is the solution. I didn't know that there are limitations. And because of this notice, I thougth this is some non standard edge stuff.
> NOTE: If you will enable Zip64 writing then you will need zip extractor with Zip64 support to extract archive.

It seems, all common current zip-apps can open these archieves.

Thanks and regards, Phil
